### ISSUE TITLE
EarthSatellite angles stored internally as radians leads to unexpected behavior

### ISSUE THREAD

**Issue by OutboundFlight** [brandon-rhodes/pyephem#103]
The EarthSatellite class represents angles internally in radians by (to all appearances) scaling them when calling setattr. This means that simple assignments between objects breaks:

`sat1._inc = ephem.degrees(90)`
`sat2._inc = sat1._inc`
`print(sat1._inc, sat2._inc)`

will produce:

> 90:00:00.0 1:34:14.9

I don't have a lot of experience with how PyEphem is architected; this may be built into the underlying libastro libraries. But one quick and dirty solution that comes to mind is to have the Python wrapper class for the libastro object have its getattr scale angles back to degrees when retrieved.

**Comment by brandon-rhodes** [comment]
This does look like a problem! I wonder if it can be fixed without breaking existing satellite programs?

At the moment I am spending all of my time on Skyfield, the replacement for PyEphem, but I will keep this issue open here for the next time I have a chance to get back to this project — it does seem inconsistent that the way to set and read the `_inc` variable use different units, and it would be nice to get it corrected, except that it will probably break all existing PyEphem programs that currently use that attribute. I'll think about what the way forward might be.

**Comment by brandon-rhodes** [comment]
Since I couldn't fix the old attributes, I added new ones. Take a look at the Quick Reference for them once I release this new version!
