### ISSUE TITLE
J2/J4 perturbations and atmospheric models

### ISSUE THREAD

**Issue by rtubio** [brandon-rhodes/pyephem#104]
Dear all,

Does PyEphem include any kind of perturbations for orbit propagation? Atmospheric models as well?

Thanks! Ricardo.

**Comment by brandon-rhodes** [comment]
Alas, no! All it can do is produce planet positions using the old VSOP87 model. It has no orbit logic of its own — its only purpose is to plan observations and do star-chart kinds of work. Have you taken a look at the AstroPy project? It is the project that I would imagine will some day expand, if it has not done so already, to include advanced techniques like propagation — like a look:

http://www.astropy.org/

**Comment by barrycarter** [comment]
Won't skyfield also do this?

**Comment by brandon-rhodes** [comment]
Skyfield currently has neither perturbations for orbit propagation. It might in the future, but at the moment it's not a project I can point him at! :)
