### ISSUE TITLE
Cygwin does not compile, but will without static 

### ISSUE THREAD

**Issue by th0ma5w** [brandon-rhodes/pyephem#106]
You'll have to excuse my ignorance. I had issues compiling pyephem on Cygwin until I removed the word "static" from before the dtoa definition in extensions/dtoa.c:3649 ... hope this helps someone! It did me. Thank you so much for such a great library!!

**Comment by brandon-rhodes** [comment]
Interesting! What is the error message that Cygwin was giving you — can you paste in the error it gave, so that I can see what its C compiler thought of that line? Thanks!

**Comment by th0ma5w** [comment]
Crap! I moved on and am not near that computer now... essentially it found a dtoa definition in one of the system libraries, and as such declaring it again and declaring static it didn't like that... Anyway, when I get back to that machine I'll try and download the clean source here again and give you the error message. It did actually list which system library, but sorry I should've included that.

**Comment by brandon-rhodes** [comment]
As it is now June, I am going to temporarily close this issue just to get it off of my list of open issues on GitHub at the moment — I hope you don't mind! As soon as you have the error message and the version of the C compiler that is complaining, I should be able to move forward with an investigation. I do not quite see why that `static` keyword should be causing a problem, but once we know the compiler and error message we can learn more about the problem.

Thanks for the bug report, and I hope we can re-open later with more information!

**Comment by th0ma5w** [comment]
Just wanted to follow up that I had updated Cygwin, and everything works fine. Not sure what the deal was. Thanks again for humoring me! And thanks for a great project.

**Comment by brandon-rhodes** [comment]
It is always nice to hear that a problem really truly was resolved, and that you were not simply forced to give up and walk away from the project — so thank you for following up!
