### ISSUE TITLE
ImportError: No module named 'ephem'

### ISSUE THREAD

**Issue by richdyer2000** [brandon-rhodes/pyephem#108]
Hi,

I've successfully installed PyEphem (also just tried ephem) on my Raspberry Pi 3 with the command 

_sudo pip install pyephem_

However, the _import ephem_ line in my python script returns the error in subject. 

My python version is 2.7.9....any ideas? I've tried googling, but only found one thread where someone had this problem and it was cured by reinstalling (which i tried!)

Cheers

Rich

**Comment by brandon-rhodes** [comment]
Two questions need to be answered: into which directory did the `ephem` module get placed, and which list of directories is Python looking through when trying to find it? The latter can be answered inside Python by doing an `import sys` followed by `print sys.path`. The question of where `pip` put PyEphem when you ran it is a bit more of a puzzle — maybe running `which pip` will give us a start by telling us where pip lives?

**Comment by richdyer2000** [comment]
Hi Brandon, 

I'm very new to this, but it looks like you've nailed it.....

- print sys.path gives me:
['', '/usr/local/lib/python3.4/dist-packages/WebIOPi-0.7.1-py3.4-linux-armv7l.egg', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-arm-linux-gnueabihf', '/usr/lib/python3.4/lib-dynload', '/usr/local/lib/python3.4/dist-packages', '/usr/lib/python3/dist-packages']

- Trying to Install pip again gives me:
Requirement already satisfied (use --upgrade to upgrade): pyephem in /usr/local/lib/python2.7/dist-packages

So, it looks like my python configuration is messed up somehow. I'll look into it, thanks!!

Cheers

Rich

**Comment by brandon-rhodes** [comment]
It looks like you are using two different versions of Python — it looks like pip is installing packages under Python 2.7, but your command line `python` is 3.4. Try running `python2.7` and see if `import ephem` works.

**Comment by richdyer2000** [comment]
Hi Brandon,

I’ll not have chance to look at this for a few days now, but I’ll get back to you when it’s working – I’ve got the additional complexity that I’m using the WebIOPI for my UI (or at least the Javascript<->Python layer) and that uses Python 3 by default.

I’ll close the issue in the meantime though!

Cheers

Rich

**Comment by custJC** [comment]
Set Python3 as the default:
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 150
