### ISSUE TITLE
object has no attribute '_raan'

### ISSUE THREAD

**Issue by maciekKolbusz** [brandon-rhodes/pyephem#110]
Hi,

I am unable to get RAAN for Solar System bodies that are predefined in pyephem. ie.:

```
Python 2.7.10 (default, Jul 14 2015, 19:46:27)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ephem
>>> Mo = ephem.Moon()
>>> Mo.compute()
>>> Mo._raan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ephem.Moon' object has no attribute '_raan'
>>> Ma = ephem.Mars()
>>> Ma.compute()
>>> Ma._raan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Mars' object has no attribute '_raan'
```

The package I have installed is:
pyephem-3.7.6.0-py2.7-macosx-10.10-intel.egg

I also tried the same code in Python 3.4 on the same machine with the same errors.

**Comment by brandon-rhodes** [comment]
As far as I know, that parameter is only defined for Earth satellites in the `libastro` library that PyEphem is build on — is there a place in the documentation where I can clarify that, to prevent confusion in the future? Let me know where to make a tweak and I will update the docs!

**Comment by maciekKolbusz** [comment]
Actually in Quick Reference Guide (http://rhodesmill.org/pyephem/quick.html) _raan is listed as an EarthSatellite's element, so I would expect it to be the attribute of ephem.Moon which is the natural satellite of Earth. I was hoping to get the right ascension of Moon's Node from this attribute.

**Comment by brandon-rhodes** [comment]
Interesting! In the terminology of the underlying libastro library, an “Earth satellite” means an artificial man-made satellite — the `Moon` class is a separate object with a dedicated set of formulae that return much higher precision solutions than would be possible if the library attempted to define the Moon’s orbit with a fixed set of parameters such as those that are used for artificial satellites (and that are so low-precision that they typically go out of date in only 2 or 4 weeks!).

I will update the text of that section of the Quick Reference to try to make that clearer.

**Comment by brandon-rhodes** [comment]
There! The improved text should appear on the web site the next time I push out a new version of PyEphem.

**Comment by maciekKolbusz** [comment]
All right, thanks for the clarification.

**Comment by brandon-rhodes** [comment]
Oh — and: to find the Moon’s ascending or descending node, I think that you would have to create a little search routine that plugs in different dates while watching the Moon’s declination, and zeros in for you on the moment when the declination reaches zero. I do not have time to code up such a solution myself at the moment, but if you look inside of the `ephem/__init__.py` module you will see several such solvers defined for things like sunrise and sunset. Following their example, you might be able to use some of the same routines to try to zero in on when the Moon’s declination is zero?

**Comment by maciekKolbusz** [comment]
Yes, I'd been doing that already, but then I found in ephemeris tables that the Nodes are moving all the time, so finding when Moon's declination or latitude is 0 only gives me the positions of Nodes at the moments of crossings. I was hoping _raan would give me the exact position of North Node computed at the given time. This was actually suggested to me by someone on StackExchange, but apparently the guy was wrong :)

**Comment by brandon-rhodes** [comment]
Oh, interesting! So while the physical reality is that the Moon crosses the equator and creates a node N1 and then a month later crosses the equator again at a new ascending node N2, you are wanting to imagine an invisible point that over the whole month is traveling between N1 and N2 in between the two moments that the Moon actually crosses the equator, even when there is nothing there to observe with your telescope? I suspect that the only way to generate such a number with PyEphem is to solve for the right ascension of both N1 and N2 and then interpolate between them to generate positions for the rest of the month.

**Comment by maciekKolbusz** [comment]
Well, I was quite surprised myself, but the explanation I got here: http://astronomy.stackexchange.com/questions/18088/why-is-the-lunar-node-in-a-daily-motion also makes sense.

**Comment by barrycarter** [comment]
Just as a minor correction, the ascending/descending node is when the moon crosses the *ecliptic*, not the equator. This requires finding when the moon's ecliptic latitude is 0.

It's possible the nodes given in the ephemeris in the linked stackexchange question are just linear drifts between when the moon is actually at an ascending/descending node. This would be useful if you considered the moon's orbit an ellipse and needed to know where to set the ascending node in your calculation.

Also, note that if the moon has an ascending/descending note close a new or full moon, we have a solar or lunar eclipse.

**Comment by brandon-rhodes** [comment]
Thanks, I have updated my earlier comment to say “ecliptic”!
