### ISSUE TITLE
lat long output different from orbitron

### ISSUE THREAD

**Issue by hirokun2016** [brandon-rhodes/pyephem#112]
Hi,
   I tried to use the pyephem library to get the lat, long of a particular satellite. However, when I compare this to what was outputted by Orbitron, the latitude was different. Why is this different? 

 Output from my code:
   Lat: -50.675605
   Lon: -153.489527

Orbitron: 
   Lat : 50.8527ｰ S
   Lon: 153.4899ｰ W

Here is my code:

```
import numpy as np
import ephem
import datetime
import functions
from datetime import timedelta, datetime
from math import degrees


name_ = "SATELLITE"
tle1 = "1 41463U 98067HT  16264.56991668  .00008327  00000-0  11928-3 0  9991"
tle2 = "2 41463  51.6441 300.8543 0000382  62.9562  67.6735 15.57105765 22715"


sat = ephem.readtle(name_,tle1,tle2)

strDate = "2016-09-21 10:05:47"
date_obj = datetime.strptime(strDate,'%Y-%m-%d %H:%M:%S')
date_ = date_obj + timedelta(hours=-9)
sat.compute(date_)
print("longitude: %f - latitude: %f" % (degrees(sat.sublong), degrees(sat.sublat)))
```

**Comment by brandon-rhodes** [comment]
There are many possible sources of difference.

* Are the two libraries using the same time zone data?
* Are they loaded with the same leap second table, or could they be several seconds off from each other in how they are interpreting the date and time you provided?
* Do they both use the same version (there are several!) of the SGP4 orbital propagation algorithm?
* Are they using the same model of the Earth for computing latitude and longitude, or is one of them using a spherical Earth and the other an ellipsoid?

If you examine the source code of Orbitron and compare its steps to the steps that PyEphem takes, I am sure you will find the difference — maybe one of the items that I thought of above, but maybe instead some difference that I have not thought of yet. I find that adding lots of `print` statements to both pieces of code can help me understand where the numbers diverge!

**Comment by brandon-rhodes** [comment]
I am going to close this for now, but please re-open it if you ever get the chance to paste in the details I listed so that I can take a look at the problem!
