### ISSUE TITLE
Defining a satellite with its keplerian elements

### ISSUE THREAD

**Issue by rtubio** [brandon-rhodes/pyephem#116]
I am trying to use PyEphem in order to carry out some preliminary mission analysis calculations. In this case, I need to define the spacecraft in terms of potential altitude, inclination, RAAN and such; instead of using any pre-defined spacecraft (either from a database or through a TLE).

In the documentation, I've seen that this option is supported by directly changing the parameter from the "EarthSatellite" body type. The following is the list of parameters to be changed:

- _epoch
- — Reference epoch
- _n — Mean motion, in revolutions per day
- _inc — Inclination (°)
- _raan — Right Ascension of ascending node (°)
- _e — Eccentricity
- _ap — Argument of perigee at epoch (°)
- _M — Mean anomaly from perigee at epoch (°)
- _decay — Orbit decay rate in revolutions per day, per day
- _drag — Object drag coefficient in per earth radii
- _orbit — Integer orbit number of epoch

Any example with the amount of parameters that necessarily need to be changed?

Beforehand, I would say that "M (mean anomaly)" and "decay", "drag" and "orbit" should be updated automatically once the other ones have been set. Am I right?

**Comment by brandon-rhodes** [comment]
I am not aware that the `libastro` library beneath PyEphem does any adjustment to one parameter based on any of the others — as far as I know, these parameters are all inputs; none of them are based on any of the others.

**Comment by brandon-rhodes** [comment]
I am going to close this for now, but please re-open it if I can answer your question more completely!
