### ISSUE TITLE
Handling Bad Comet Data

### ISSUE THREAD

**Issue by Bernmeister** [brandon-rhodes/pyephem#117]
I use Pyephem to compute comet rise/set and other attributes.  The comet source data comes from the Minor Planet Center and the daily data file is [here](http://www.minorplanetcenter.net/iau/Ephemerides/Comets/Soft03Cmt.txt).

A few days ago my code crashed with a segmentation fault (running Ubuntu 14.04 64 bit) and I tracked the problem to bad data, specifically dodgy data for one comet:

`C/2015 O1 (PANSTARRS),e,127.2101,299.8493,89.5718,******,0.0000000,0.99999273,0.0000,02/18.9371/2018,2000,g  6.5,4.0`

Those * should be a number.  The segmentation fault occurred on calling `.next_rising/.next_setting`, rather than `readdb`.

I noticed that after reading in data, creating an object (comet) and calling `compute`, some values are `nan`.  To avoid the segmentation fault, I check specific attributes of the object for `nan`.

One alternative is to parse the comet data myself and screen out dodgy data.  Looking at the data format and all its variants, it's a bit of a nightmare.

I realise that XEphem is doing the underlying reading of the data and so Pyephem can only really act as a messenger, however, is there any other way to prevent a segmentation fault apart from checking an object's fields for `nan`?

For reference, here is a script to demonstrate the issue:

```
#!/usr/bin/env python3

import ephem, math

city = ephem.city( "Sydney" )
line = "C/2015 O1 (PANSTARRS),e,127.2101,299.8493,89.5718,512987,0.0000000,0.99999273,0.0000,02/18.9371/2018,2000,g  6.5,4.0"
comet = ephem.readdb( line )
comet.compute( "2017/02/10" )
rising = city.next_rising( comet )
setting = city.next_setting( comet )
print( comet.earth_distance, comet.phase, comet.size, comet.sun_distance, rising, setting )

city = ephem.city( "Sydney" )
line = "C/2015 O1 (PANSTARRS),e,127.2101,299.8493,89.5718,******,0.0000000,0.99999273,0.0000,02/18.9371/2018,2000,g  6.5,4.0"
comet = ephem.readdb( line )
comet.compute( "2017/02/10" )
#rising = city.next_rising( comet ) # Uncomment to produce a Segmentation fault.
#setting = city.next_setting( comet ) # Uncomment to produce a Segmentation fault.
print( comet.earth_distance, comet.phase, comet.size, comet.sun_distance, rising, setting )
```

**Comment by brandon-rhodes** [comment]
I don't currently know of a way to avoid the fault without, as you mention, a manual check. I will keep this issue open in case any time is ever found to work on it, though — but my attention will likely be on Skyfield, the replacement for PyEphem that I just brought to version 1.0. Hopefully I will soon be adding comet support to it!

**Comment by brandon-rhodes** [comment]
Now that comets are supported by Skyfield, I'm happy to finally return to this issue and close it!
