### ISSUE TITLE
moon rise and set times are off by hours 

### ISSUE THREAD

**Issue by soundreactor** [brandon-rhodes/pyephem#121]
Hi 

somehow i'm getting very different moon rise and set values compared to two other web services:

http://www.mooncalc.org/#/46.5437,6.6577,10/2017.05.09/00:11/1/0
http://www.heavens-above.com/moon.aspx?lat=46.5437&lng=6.6577&loc=KE&alt=716&tz=CET
(on the second link the time has to be set manually to correspond with the test data)

```
import ephem
import datetime as dt
import time


# ~ Lausanne, Switzerland
input_lat = '46.5437'
input_lon = '6.6577'


print("Moon Zenith 0-1")

# ts = time.time()
# st = dt.datetime.fromtimestamp(ts).strftime('%Y/%m/%d %H:%M')
# print(st)
d = ephem.Date("2017/5/9 00:11:00")

obsvr = ephem.Observer()
obsvr.pressure = 0
obsvr.horizon = '-0:34'
obsvr.elevation = 644

obsvr.lat = input_lat
obsvr.lon = input_lon
obsvr.date = d # noon EST

print(obsvr.date)

pr = obsvr.previous_rising(ephem.Moon())
ps = obsvr.previous_setting(ephem.Moon())
nr = obsvr.next_rising(ephem.Moon())
ns = obsvr.next_setting(ephem.Moon())

print("")
print("pr "+str(pr))
print("ns "+str(ns))
print("nr "+str(nr))
print("ps "+str(ps))
print("")
#determine if we have a moon day or night.
if(ns < nr):
    # print(obsvr.next_transit(ephem.Moon()))
    print("we have m dayyy")
    val3 = 0.5+(0.5-abs(((d-pr)/(ns-pr))-0.5))
else:
    print("we have m night")
    val3 = abs(((d-ps)/(nr-ps))-0.5)
# trying to get a 0-1 value for 0 for nadir and 1 for zenith
print(val3)
```
the output i get is

Moon Zenith 0-1
2017/5/9 00:11:00

pr 2017/5/8 13:17:43  <----- this should be ~ 19:25 according to the other pages
ns 2017/5/9 01:33:04 <----- this should be ~ 05:49 according to the other pages
nr 2017/5/9 14:03:21
ps 2017/5/8 00:51:17

we have m dayyy
0.6116041068736761

**Comment by albertw** [comment]
This is odd. When I run your code (ipython2.7, macos, pyephem 3.7.6.0) I get:

Moon Zenith 0-1
2017/5/9 00:11:00

pr 2017/5/8 16:23:35
ns 2017/5/9 03:48:56
nr 2017/5/9 17:24:34
ps 2017/5/8 03:22:32

You are UTC+2 so that's pretty close to a next rise of 19:25 local and next set 05:49 local.

But since all pyephem/libastro calculations are based on UTC I don't see how we're getting different results.

**Comment by soundreactor** [comment]
somehow i'm getting the same output like you now. 😧 

there might have been a problem because i did not load the file locally but over an smb connection from another machine.

thanks for enlightening me about the UTC thing. i'm getting good numbers now. all UTC.. but good.😬

**Comment by albertw** [comment]
Good that you are getting the right numbers anyway! pyephem does let you convert a ephem.Date to a   datetime object in local time if that's any help to you http://rhodesmill.org/pyephem/date.html#time-zones

**Comment by soundreactor** [comment]
great! just what i was looking for. 👍

**Comment by brandon-rhodes** [comment]
Thank you, @albertw, for diving in and providing help while I was busy with PyCon! Since it sounds like @soundreactor has working code now, I'll tentatively close this issue, but please feel free to re-open it if there is a further issue here to explore.
