### ISSUE TITLE
Bug : inverted setting and rising?

### ISSUE THREAD

**Issue by lblt** [brandon-rhodes/pyephem#122]
Hello!

I'm trying to get the hours of sunset and sunrise in Abu Dhabi. To set the example, I've taken 2017/05/20 00:00:00 as the time of reference.
I've obtained a very strange result using ephem and I can't see what I'm doing wrong, so perhaps it's a bug...

**System:** 
Ubuntu 16.04 Python 2.7

**Steps to reproduce:**
I have used astral to double check what I was expecting.
First python file, ephem: 
```
#!/usr/bin/python
# -*- coding:utf-8 -*-


import ephem
import datetime

obs = ephem.Observer()
obs.pressure = 0
obs.horizon = '-6'
obs.lat, obs.lon = 24.492, 54.439
obs.elevation = 0

obs.date = datetime.datetime.strptime("2017-05-20 00:00:00", "%Y-%m-%d %H:%M:%S")

print obs.date
    
next_rising = obs.next_rising(ephem.Sun())
next_setting = obs.next_setting(ephem.Sun())

print("next rising", next_rising)
print("next setting", next_setting)
```
Second python file, astral:
```
#!/usr/bin/python
# -*- coding:utf-8 -*-

from astral import Astral
import datetime
        
city_name = 'Abu Dhabi'

a = Astral()

a.solar_depression = 'civil'

city = a[city_name]

timezone = city.timezone

date = datetime.datetime.strptime("2017-05-20 00:00:00", "%Y-%m-%d %H:%M:%S")

print(date)

sun = city.sun(date)

print('Sunrise: %s' % str(sun['sunrise']))
print('Sunset:  %s' % str(sun['sunset']))
```
**Observations:**
Here are the results I got (I should get the same results):
ephem
```
2017/5/20 00:00:00
('next rising', 2017/5/20 14:29:26)
('next setting', 2017/5/20 01:30:57)
```
astral
```
2017-05-20 00:00:00
Sunrise: 2017-05-20 05:37:01+04:00
Sunset:  2017-05-20 19:01:05+04:00
```
The ephem result is very strange: a sunrise at 14:29UTC i.e. 18:29+4 in Abu Dhabi is kind of bizarre... 
On the other hand the astral result is coherent.

**It looks like that sunrise and sunset have been inverted in the ephem result.**

Thanks in advance for your insight on that question!!

**Comment by barrycarter** [comment]
If you do `print obs`, you'll see the latitude is 1403:17:17.6 and the longitude is 3119:07:29.8, both of which are approximately 57 times the value you entered. In other words, you should be using radians in your input, not degrees.

**Comment by lblt** [comment]
@barrycarter thank you very much!

**Comment by lblt** [comment]
Perhaps a change is needed in the example about Atlanta in the documentation you can find at that page: http://rhodesmill.org/pyephem/rise-set.html
Indeed if I'm not mistaking the latitude and longitude are given in degree in that example.

**Comment by drbitboy** [comment]
from http://rhodesmill.org/pyephem/quick.html#coordinate-conversion:

    When setting an angle attribute in a body or observer, or creating angles yourself,
    you can provide either floating-point radians or a string with degrees or hours [...]

So the Atlanta example at that URL is correct, but It would not hurt to append a comments like

    atlanta.lat, atlanta.lon = '33.8', '-84.4'    # strings => degrees North, East

**Comment by lblt** [comment]
@drbitboy thank you very much for the time you've taken! My bad, I went too quickly through the documentation apparently...

**Comment by drbitboy** [comment]
no need say your "bad" - if I had a nickel for every time I missed something like this ...

Anyway, I get to look like a good guy, and maybe that example gets improved.

**Comment by barrycarter** [comment]
While I understand there's a difference between the string "33.8" and the number "33.8", I'd argue this is a confusing design; let's keep this issue open until our benevolent dictator (Brandon) decides on if he wants to change it.

Also "my bad" just means "my mistake" and is fairly minor :)

**Comment by brandon-rhodes** [comment]
It was terrible design, and in the replacement I am slowly writing for PyEphem (named "Skyfield") there are, happily, no distinctions like this between a value delivered as a number versus a string.

I'll add a comment to the documentation there — thanks for the idea!
