### ISSUE TITLE
sun.set_time sun.set_az returns None if it is utc 00 00 00

### ISSUE THREAD

**Issue by me-at-git-hub** [brandon-rhodes/pyephem#123]
pyephem 3.7.6.0  in python 3.5.2 on ubuntu 16.04
regarding sun.set_time  and  sun.set_az
If sunset would have  computed to be 00:00:00 utc for a location, pyephem returns (prints) a None for the set_time.  This then also causes a None to be returned (printed) for set_az where clearly there ought to be a value for set_az returned.   Errors, multiple errors if the code is more dense.  When trying to put these 'None' tuple values into a variable there is an attribute error, since, well, they don't exist. 

AttributeError: 'NoneType' object has no attribute 'tuple'
 
At the example location below, the problem manifests only on dates where sun.set_time would have computed to be 00:00:00 utc (as best I can tell)  such as 2017/5/2 for the example lon lat elev
I believe that the specific computed sunset time of 00 00 00 in utc is the problem.
It may manifest on any location and date combination where the rounded set_time rounds to 00:00:00 utc.  I have done some, but not thorough testing of the theory.  However, > one hundred other dates work as expected.  The quirk can be worked around, for now.  Even if the set_time is caught with an if statement, and one forces the variable that would have held set_time to 00:00:01, still,  the set_az is more problematic since it seems to never be computed at all if set_time is computed to be None by pyephem, thus requiring discrete code for that one case, or set_az needing to be approximated from the day before and the day after.  Not ideal.  But thank you for making this package available, with all the work put into this release and past fixes.  Good job!

I am new to pyephem and github. If I am doing something wrong, or taking a wrong approach to this, please advise.  Thank you.

---------------------
2017/5/1 10:22:12 is the rise_time in utc
70:40:28.9 is the rise_az
2017/5/1 23:59:25 is the set_time  in utc
289:32:25.0 is the set_az

2017/5/2 10:21:07 is the rise_time in utc
70:17:50.3 is the rise_az
None is the set_time  in utc
None is the set_az

2017/5/3 10:20:04 is the rise_time in utc
69:55:30.0 is the rise_az
2017/5/3 00:00:16 is the set_time  in utc
289:54:54.9 is the set_az

Traceback (most recent call last):
  File "ephem_bug_test.py", line 42, in <module>
    sunsetTime = sun.set_time.tuple()[0]
AttributeError: 'NoneType' object has no attribute 'tuple'

---------------------

```python
import datetime
import ephem

home = ephem.Observer()
home.long = '-78.372934'
home.lat = '35.959081'
home.elevation = 65
sun = ephem.Sun()

for day in range(1,4):
    home.date = (2017, 5, day, 12, 0, 0)
    sun.compute(home)
    print(sun.rise_time, 'is the rise_time in utc')
    print(sun.rise_az, 'is the rise_az')
    print(sun.set_time, 'is the set_time  in utc')
    print(sun.set_az, 'is the set_az')
    print()

home.date = (2017, 5, 2, 12, 0, 0)
sun.compute(home)
sunsetTime = sun.set_time.tuple()[0]
```

**Comment by barrycarter** [comment]
Isn't this expected behavior, though? If the sun sets at midnight in whatever time zone you're using, it really doesn't set at all today and, therefore, there's no set time or set azimuth.

Try using the local time zone or perhaps something like next_rise or next_set to see if that helps?

**Comment by brandon-rhodes** [comment]
The old attributes like `rise_time` and `set_time` are indeed unreliable, and recommended only now for Earth satellites. Try switching to routines like `next_rising()` and see if you get better results! Here is some documentation to get you started:

http://rhodesmill.org/pyephem/quick.html#transit-rising-setting

**Comment by me-at-git-hub** [comment]
Thank you kindly gentlemen.  I will change my code to utilize previous_rising and next_setting for the sun, perhaps getting to it tomorrow.  I'll post again, one more time, to confirm when all is resolved.

**Comment by me-at-git-hub** [comment]
A bit of life has happened in 10 months. I did not exactly get to this 'tomorrow', but now I did today, testing a workaround on pydroid3, as follows.

'''# testing a workaround on pydroid3 with pyephem 3.7.6.0 installed

# my test from pyephem forum. The sun.set_time 'none' issue
# remains a problem if using sun.set_time and sun.set_az
# but is avoided if instead using sun.az and sun.alt
# when time is explicitly  0, 0, 0 (midnight utc).
# Note that .az and .alt are 'slightly' different than the
# .set_az and .set_alt methods had returned previously.
# I shall use .az and .alt instead, using .alt to determine rise and set,
# doing this as a workaround from previously trusting .set_time .set_az
# .set_alt and the rise equivalents.  I assume the problem with .rise_az
# and rise_alt will this way be similarly avoided. Concluding then
# there persists a problem with the methods sun.rise_time and
# sun.set_time if the calculation result is very close to or at 00:00:00 utc.
# There is no such problem with sun.az and sun.alt even at exactly 
# 00:00:00 utc.

import datetime
import ephem 

home = ephem.Observer() 
home.long = '-78.372934' 
home.lat = '35.959081' 
home.elevation = 65 
sun = ephem.Sun() 

print('Now using directly entered datetime values similar to what was previously')
print('calculated by .set_time,  here is the result, proving a workaround.')
print()

hDate = (2017, 5, 1, 23, 59, 25), (2017, 5, 2, 0, 0, 0), (2017, 5, 3, 0, 0, 16)

for hDay in range(0,3):
    home.date = hDate[hDay]
    sun.compute(home) 
    # print(sun.rise_time, 'is the rise_time in utc') 
    # print(sun.rise_az, 'is the rise_az') 
    print(home.date, 'which should be sunset in utc at the location.') 
    print('instead of using sun.set_time (which was problematic if occuring midnight utc).')
    print(sun.az, 'is the sun.az which happens to be sunset at this location')
    print(sun.alt, 'is sun.alt, what sun.set_alt calls sunset, but .set_alt returns None if at midnight utc')  
    print() 
    
    
print('To show again that .set_time .set_az .set_alt and the .rise equivalents still')
print('have issues, on an Android environment as well, very near or at midnight,')
print('watch those methods throw an exception again.')

home.date = (2017, 5, 2, 12, 0, 0) 
sun.compute(home) 
sunsetTime = sun.set_time.tuple()[0]
'''

And here is the result, proving the workaround.

Now using directly entered datetime values similar to what was previously
calculated by .set_time,  here is the result, proving a workaround.                                                                                             
2017/5/1 23:59:25 which should be sunset in utc at the location.                                                                                                instead of using sun.set_time (which was problematic if occuring midnight utc).                                                                                 289:32:22.1 is the sun.az which happens to be sunset at this location                                                                                           0:00:03.0 is sun.alt, what sun.set_alt calls sunset, but .set_alt returns None if at midnight utc                                                               
2017/5/2 00:00:00 which should be sunset in utc at the location.                                                                                                instead of using sun.set_time (which was problematic if occuring midnight utc).
289:37:32.2 is the sun.az which happens to be sunset at this location
-0:05:25.3 is sun.alt, what sun.set_alt calls sunset, but .set_alt returns None if at midnight utc

2017/5/3 00:00:16 which should be sunset in utc at the location.
instead of using sun.set_time (which was problematic if occuring midnight utc).
289:54:54.6 is the sun.az which happens to be sunset at this location
0:00:00.4 is sun.alt, what sun.set_alt calls sunset, but .set_alt returns None if at midnight utc

To show again that .set_time .set_az .set_alt and the .rise equivalents still
have issues, on an Android environment as well, very near or at midnight,
watch those methods throw an exception again.
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_hackrun/iiec_hackrun.py", line 29, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_hackrun/iiec_hackrun.py", line 28, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 51, in <module>
AttributeError: 'NoneType' object has no attribute 'tuple'

[Program finished]

I hope that settles it for now.  sun.set_time  etc, has an issue.  Use .previous_rising and .next_setting instead to get very close to rise and set times, and then use the .az and .alt methods with explicity entered home.date, and the problem(s) are avoided.  Enjoy the sunsets that continue to be real again, instead of 'None'.

**Comment by brandon-rhodes** [comment]
> Thoughts such as providing some insight to newbies of what attributes are older and unreliable, compared to the newer and reliable ones? As a newbie I had no idea until I actually encountered some problems. Is there a document page that specifically points out old problems and their newer and better solutions? Or should we go to documentation for xephem if that is where the actual problem has its source?

Those are good questions. To answer them:

1. The code has been raising a warning since 2007 about these old body attributes, to tell users about the replacement. Unfortunately, though, Python only shows users warnings if they ask, and most programmers don't.
2. So I'll add a mention of them to the Quick Reference, so folks know to avoid them.
