### ISSUE TITLE
Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by eamanu** [brandon-rhodes/pyephem#124]
When I do `python setup.py build_ext -i` 

I have this error:

```
running build_ext
building 'ephem._libastro' extension
error: Unable to find vcvarsall.bat
```

I am in a Windows 7 Ultimate edition Service Pack 1

**Comment by brandon-rhodes** [comment]
I have not used Windows for several years, so the best approach is probably to Google for a solution that might fix your system so that Python can compile things:

https://www.google.com/search?q="error%3A+Unable+to+find+vcvarsall.bat"

**Comment by eamanu** [comment]
Oh yes... I found the problem. It's a problem with the Visual Studio I need for compile Python and Python module. I started to use Windows 15 days ago, so I don't understand nothing.

Thanks!!

**Comment by brandon-rhodes** [comment]
I'm glad it's working now — and I'm glad your persistence paid off!
