### ISSUE TITLE
Star catalogue is missing 21 of the 57 common navigational stars

### ISSUE THREAD

**Issue by paulross** [brandon-rhodes/pyephem#127]
The missing stars, by 'common' name, are: Acamar, Acrux, Adhara, Alkaid, Alpheratz, Ankaa, Atria, Avior, Diphda, Eltanin, Formalhaut, Gacrux, Gienah, Hadar, Menkent, Miaplacidus, Mirfak, Rigil Kentaurus, Sabik, Suhail, Zubenelgenubi.

There is some differences between these 'common' names (found in Nautical Almanacs and named by the IAU-CSN) and formal star catalogues. For example:

* Almanac/IAU-CSN name 'Eltanin' is formally known as 'Gamma Draconis' in the catalogue.
* Almanac/IAU-CSN name 'Hadar' is formally known as 'Beta Centauri' in the catalogue.
* Almanac/IAU-CSN name 'Rigil Kentaurus' is formally known as 'Alpha Centauri A' in the catalogue.

Sources:

Star names:
"IAU Catalog of Star Names (IAU-CSN)":
https://www.iau.org/science/scientific_bodies/working_groups/280/
Which links to:
http://www.pas.rochester.edu/~emamajek/WGSN/IAU-CSN.txt

Star names and navigation data:
Her Majesty's Nautical Almanac Office Publications ('Almanac'):
* NP314-18 "The Nautical Almanac" (2017).
* DP330 "NavPac and Compact Data" (2015).
* NP303 (AP3270) "Rapid Sight Reduction Tables for Navigation" (2012).

Star astronomical data ('the catalogue'):
https://heasarc.gsfc.nasa.gov/cgi-bin/W3Browse/w3hdprods.pl

**Comment by brandon-rhodes** [comment]
Thanks for the contribution — and, wow, you even added tests! I'm not sure how soon a new PyEphem will be released, since at the moment I'm focusing on Skyfield, but I'm happy to see this code landed either way!
