### ISSUE TITLE
PyEphem compatibility with new versions of Python

### ISSUE THREAD

**Issue by newuser86** [brandon-rhodes/pyephem#131]
I am new to Python and PyEphem.  I have found an issue using pyephem 3.7.6.0 and python 3.6.3 on Windows 10.  While testing the Observer example in the Quick Reference, I found a problem creating an Observer.  Below is the example:

```
>>> lowell = ephem.Observer()
>>> lowell.lon = '-111:32.1'
>>> lowell.lat = '35:05.8'
>>> lowell.elevation = 2198
>>> lowell.date = '1986/3/13'
>>> j = ephem.Jupiter()
>>> j.compute(lowell)
>>> print(j.circumpolar)
False
>>> print(j.neverup)
False
>>> print('%s %s' % (j.alt, j.az))
0:57:44.7 256:41:01.3
```

When I type this line-by-line into the Python Shell, it works perfectly fine.  But if I put the exact same code into a .py program, it will throw the following error when executed:

```
Traceback (most recent call last):
  File "C:/Python/Programs/ephem observer.py", line 1, in <module>
    import ephem
  File "C:/Python/Programs\ephem.py", line 8, in <module>
    gatech = ephem.Observer()
AttributeError: module 'ephem' has no attribute 'Observer'
```

I installed Python 2.7.14 to test this issue on an older version, and the code runs without error.

1) For Python 3.6.4, I am curious why the code works when typed line-by-line into the shell, but does not work if you run it all as a program.
2) What is the latest version of Python that PyEphem is known to work with?

Jason

**Comment by brandon-rhodes** [comment]
The problem appears to be that you are not loading the actual "ephem" package (whose module path would be `.../ephem/__init__.py`), but instead a file named `ephem.py` that's sitting in your `C:/Python/Programs` directory. If you'll move, remove, or rename that file, then `import` won't see it and should correctly load the actual PyEphem package from its install directory.

Let me know what you discover!

**Comment by brandon-rhodes** [comment]
I'm going to close this for now, pending further information from you on whether the first proposed solution worked. Please re-open if you are still having trouble.
