### ISSUE TITLE
body.compute() returns garbage instead of raising error for invalid TLE/date combo

### ISSUE THREAD

**Issue by jessehersch** [brandon-rhodes/pyephem#134]
Environment: linux, python 3.6.3, pyephem==3.7.6.0

This is a minor issue we ran into, had some code that was generating a bad TLE/date combination. I would have expected body.compute(datetime) to raise an error here but it doesn't.

repro:
```python
import math
import ephem
import datetime

def main():
    # note the date of the ephemeris here: 405 days after start of 2018
    line_1 = '1 xxx12U 19012A   18405.83273452 0.00000000  00000-0 -00000-0 0    13'
    line_2 = '2 xxx12  97.4399 286.0924    9213  27.2317 163.7906   15.207979    06'
    sat = ephem.readtle('unused', line_1, line_2)
    # this time is a few hundred days prior to the time in the TLE
    t = datetime.datetime(2018, 2, 9, 15, 27, 14)
    # expected some error thrown here. instead, it returns happy 
    sat.compute(t) 
    # and garbage is produced for sublat. sublong is likely suspect...
    lat, lon = math.degrees(sat.sublat), math.degrees(sat.sublong)
    print(sat.sublat, sat.sublong)
    print(lat, lon)
    
if __name__ == '__main__':
    main()
```

Output:
```
1389660529:33:00.8 -11:28:55.6
nan -11.482110631624314
```
Expected: sat.compute(t) line should raise a ValueError or similar. Or perhaps ephem.readtle() should raise because the time for the ephemeris is so far beyond the start of 2018?

**Comment by jezemine** [comment]
here's another example hit today:
```python
import ephem
import arrow
line_1 = "1 xxx60U 19060A   17251.93747685 0.00000000  00000-0 -00000-0 0    12"
line_2 = "2 xxx60  97.4327 286.0806      91 144.1179  56.0292   15.186622    02"
sat = ephem.readtle('unused', line_1, line_2)
current = arrow.get("2018-09-08 22:30:00+00:00").datetime
sat.compute(current)
x = sat.sublat, sat.sublong
print(x)

(nan, 0.6032775044441223)
```

**Comment by jessehersch** [comment]
another example if you need it:
sat.sublat, sat.sublong=(nan,-0.8724347902811265) when observed at 2018-09-22 00:00:15+00:00 for:
```
1 99504A          17265.00000000  .00000000  00000-0  00000-0 0 00001
2 99504 053.0192 135.0003 0008686 268.4253 091.5764 15.22029182000014
```

root cause appears to be TLE epoch is too old. :)

**Comment by jessehersch** [comment]
I don't mean to raise on reading the TLE. I mean raise when calling `sat.compute(date_that_is_much_bigger_than_tle_epoch)` since the satellite's position is nan when that's done. 

Not clear to me how returning nan is better than raising an error. But if other users of pyephem can somehow make some use of the nan retval, ok. I can just look for it and deal with it.

btw thanks for creating pyephem!  it's of great use to me. :)

**Comment by jessehersch** [comment]
Also, pyephem is already raising like I expect if I pick a date that's really much bigger than the epoch, so there's already precedent for what I am talking about:
```
import ephem
import arrow
line_1 = "1 xxx60U 19060A   17251.93747685 0.00000000  00000-0 -00000-0 0    12"
line_2 = "2 xxx60  97.4327 286.0806      91 144.1179  56.0292   15.186622    02"
sat = ephem.readtle('unused', line_1, line_2)
current = arrow.get("2030-01-01").datetime
sat.compute(current)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-556011e93f59> in <module>()
----> 1 sat.compute(current)

ValueError: TLE elements are valid for a few weeks around their epoch, but you are asking about a date 4497 days from the epoch
```
But a date that is not quite so far away, but still too far from the TLE epoch to produce good values does this:
```
In [17]: current = arrow.get("2018-09-08 22:30:00+00:00").datetime
In [18]: sat.compute(current)
In [19]: sat.sublat, sat.sublong
Out[19]: (nan, 0.6032775044441223)
```

**Comment by brandon-rhodes** [comment]
Returning to this issue three years later, I think I'm happy leaving this situation as-is. A hard exception for too-far-from epoch helps educate programmers about the limits of a TLE. But raising a hard exception when their programs are well-crafted and are asking about a date well in-bounds for the TLE, merely because the TLE happens to return `nan` values because of reentry or other anomaly, seems heavy-handed. Given how many years PyEphem has been calmly not raising exceptions in this case, I don't think I want to switch this to a crash for folks who are already being careful about the dates they ask about and aren't expecting their program to error out.

But for what it's worth, I definitely learned my lesson here, and neither `sgp4` nor Skyfield have checks like this or raise exceptions just because they're unhappy about how old a TLE is!
