### ISSUE TITLE
Accuracy of ephem.localtime()

### ISSUE THREAD

**Issue by tomfowle** [brandon-rhodes/pyephem#135]
Microsoft Windows [Version 10.0.16299.248]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ephem
>>> n = ephem.now()
>>> print(ephem.Date(n))
2018/3/13 01:32:51
>>> print(ephem.localtime(n))
2018-03-13 12:32:51.000001
>>> n = ephem.now()
>>> print(ephem.Date(n))
2018/3/13 01:36:33
>>> print(ephem.localtime(n))
2018-03-13 12:36:33.000001
>>>

Is the output I am getting from ephem.localtime()  "normal'? I draw your attention to the .000001 at the end of the output.

**Comment by brandon-rhodes** [comment]
Yes, that's normal; Windows returns times that are multiples of one second, but the rounding that turns seconds into floating-point numbers inside PyEphem runs into the inherent inaccuracy of floating point numbers.

**Comment by brandon-rhodes** [comment]
I am not sure why I didn't close this issue after answering the question. I might have been distracted in 2018.
