### ISSUE TITLE
wrong value in ephem.delta_t('0')

### ISSUE THREAD

**Issue by gaaraxpo** [brandon-rhodes/pyephem#141]
based on [this site](https://eclipse.gsfc.nasa.gov/SEhelp/deltaT.html), the value of `ephem.delta_t('0')` is 10580 seconds
but using `pyephem`, the value of that is `4293967262420208.5`

I think there is some kind of mistake in here.

**Comment by barrycarter** [comment]
Might be a special case since there is technically no year zero. Could you try with nearby dates?

**Comment by gaaraxpo** [comment]
What do you mean by 'no year zero'? year zero is a year before year one, isn't it?
The other dates I tried are pretty accurate

**Comment by barrycarter** [comment]
Technically, the year before "1 CE" (or "1 AD") is "1 BCE" (or "1 BC"). However, some astronomy programs use "0" to mean "1 BCE", so I could be wrong here. If the other values work well, I'm guessing pyephem is dividing by a number close to 0 (the input year) and getting the wrong answer.

**Comment by brandon-rhodes** [comment]
Interesting. It looks like the date conversion routine, having originally been written for an interactive application, lets the user omit fields if they want to leave them the same. So if they're at `1980/5/1`, for example, and want to jump to the beginning of June, they could say `/6/1` and not write the year again.

Unfortunately, the value zero is used internally to the function to mean “they didn't specify a value for that; just leave the previous value alone." Or at least I think that's the intention:

https://github.com/brandon-rhodes/pyephem/blob/master/libastro-3.7.7/formats.c#L247

So when you pass a year of zero, it's just leaving the year uninitialized, using whatever bits were already stored in memory there to choose an arbitrary year.

So I suppose that the fault is in my own code:

```
     int year, month = 1;
```

It leaves year uninitialized!

So I'll see about fixing that.
