### ISSUE TITLE
Sphinx warning: FAQ not referenced

### ISSUE THREAD

**Issue by 1kastner** [brandon-rhodes/pyephem#145]
When I generated the documentation, I got the following warning:
`pyephem\ephem\doc\faq.rst: WARNING: document isn't included in any toctree`
And indeed it is not. Would you want to include it? Until now the collection of question/answer-pairs is not that large, so maybe it could also be removed? Or kept for historical reasons?

**Comment by brandon-rhodes** [comment]
The FAQ indeed didn't wind up growing into something substantial enough to include. We should think about whether there's somewhere else in the docs that the information in the single FAQ answer could go.

**Comment by 1kastner** [comment]
Was it a real question which came up from somewhere or did you rather comment on your own design decision? It is in fact a nice-to-know but in my opinion not some information outstanding for this library. Maybe this information could be rather put into the doc-string of the class? Maybe that is a better place?

**Comment by brandon-rhodes** [comment]
Re-reading it, I'll make the guess that it was certainly not a literal "frequently asked question"!
