### ISSUE TITLE
Orbit propagation, considering Moon, Sun, zonal harmonics, Jupiter and Venus

### ISSUE THREAD

**Issue by Tarlan0001** [brandon-rhodes/pyephem#147]
I was suggested to use PyEphem as the best way to propagate the orbit of a satellite. 

I'm going to propagate in 1 year, considering the effects of Moon, Sun, zonal harmonics and probably, Jupiter and Venus. What I really need, is to find the change in argument of perigee in 1 year under the mentioned perturbations.

Does PyEphem really capable to do this?

**Comment by Tarlan0001** [comment]
Thank you!
Is it possible to do this math with PyEphem or Skyfield? Or, I have to solve the differential equations using another libraries?

**Comment by brandon-rhodes** [comment]
PyEphem and Skyfield simply produce positions using pre-calculated tables for the planets and Moon, and for Earth satellites using the SGP4 algorithm. My guess is that you'll next need to study SGP4 and understand its design decisions and limitations and simplifications and sources of error, in order to generate your own custom approach to trying to predict the satellite orbit out much farther than SGP4 can.

**Comment by Tarlan0001** [comment]
Do you mean, that [this](http://rhodesmill.org/pyephem/quick.html#bodies-with-orbital-elements) calculates the position of objects on the basis of their keplerian elements using SGP4?

Oh, ok. I thought, PyEphem/Skyfield has numerical propagator.

Thank you! We may close this question.

**Comment by brandon-rhodes** [comment]
Skyfield and PyEphem can only consume TLE's, not produce them — I use https://celestrak.com/ to download them when I'm curious where a satellite is. Producing TLE's is typically something that satellite tracking organizations in governments and private industry do. NORAD does quite a bit of work in that area, for example. You'll either need your own tracking stations to make observations of the satellite you're interested in, or else need to find a source of observations that you can combine to produce orbital elements; I've never undertaken that process myself.

**Comment by Tarlan0001** [comment]
But [here](http://rhodesmill.org/pyephem/quick.html#bodies-with-orbital-elements) the propagation initiated by orbital elements is described. That's why I'm asking about TLE's generation.

**Comment by brandon-rhodes** [comment]
“When you load minor objects like comets and asteroids” — that section is about how PyEphem lets you see the orbital elements you've "loaded" from a catalog, as described in the section just above that in the docs:

http://rhodesmill.org/pyephem/quick.html#catalog-format

When you load an `.edb` file or `.tle` file, someone else — the person who created the file — has generated the orbital parameters. PyEphem just reads them in and can tell you the position of an object on a given date predicted by those orbital elements.
