### ISSUE TITLE
pyephem package

### ISSUE THREAD

**Issue by rgoalcast** [brandon-rhodes/pyephem#149]
I have installed ephem-3.7.6.1-cp36-cp36m-win_amd64.whl
Now
I am trying to install
pip install orbit-0.2.tar.gz
but again, it required
pyephem
What package should I install ? Thank you.

**Comment by brandon-rhodes** [comment]
The official name of the package is "ephem" but it sounds like "orbit" is using the old name from a decade ago, "pyephem". Maybe "pip install pyephem" would make it happy?

**Comment by brandon-rhodes** [comment]
I'm going to close this for now, but feel free to respond with a follow-up comment and offer more details if the command I suggested doesn't help!
