### ISSUE TITLE
Sat revolution (orbit) number

### ISSUE THREAD

**Issue by darkstar007** [brandon-rhodes/pyephem#15]
Would it be possible to have a 'revolution' (i.e. the number of orbits the object has completed since launch) number included in the ephem.EarthSatellite class?

Thanks,

Matt

**Comment by brandon-rhodes** [comment]
The `sgp4` library that Skyfield uses makes this number from the TLE available. I think you should be able to get at it with:
```
print(sat.model.revnum)
```
