### ISSUE TITLE
'Sun' transits below the horizon calculated for wrong day?

### ISSUE THREAD

**Issue by onkelandy** [brandon-rhodes/pyephem#151]
Hi!
I'm using pyephem in conjunction with a smarthome tool. I want to get the altitude of the sun for a given location based on sunrise/sunset + an offset in degrees
Therefore I use the:
```
_obs.date = datetime.datetime.utcnow() # actually was 2018-09-08
_obs.horizon = str(doff) # set to a value too high
_obs.next_setting(self._orb, use_center=center).datetime() # get the sunrise with degree offset
```

The horizon defines the offset in degrees. Don't know if that gives a totally accurate result but it's good enough. Problem coming up, if doff is set higher than the sun will ever get on the requested day:
'Sun' transits below the horizon

That's pretty fine so far. So to avoid that problem I figure out noon and the position of the sun for noon to get the maximum altitude for that day. I then use that value -0.1 as the horizon doff above. I still get an error. It got obvious that the DATE is wrong. Not today but tomorrow.

`Error '06:00<sunrise+99<15:10' parsing time: 'Sun' transits below the horizon at 2018/9/9 11:18:59
`

Here are the calculations I used for my setup. I then queried the altitude for the sun at noon tomorrow, subtracted 0.01 to be sure and voila - everything works. Main problem still, that the difference even between the two days are about 5 minutes what is quite much. Is this behaviour on purpose?

midnight: 2018-09-07 23:19:29.907537+00:00, noon: 2018-09-08 11:19:19.628992+00:00, next noon: 2018-09-09 11:19:19.628992+00:00, max: 48.37995109887116, doff: 48.27995109887116, observer date 2018/9/8 11:19:20

**Comment by brandon-rhodes** [comment]
Could you provide a short Python script I could run to see the problem for myself? Thanks!

**Comment by onkelandy** [comment]
Hi Brandon!

Thanks for quick reply!! Just went through all the code to replicate the problem and found it.. in front of the screen ;)

Sorry and thanks for your work!!

**Comment by brandon-rhodes** [comment]
No problem — I'm glad your issue is resolved! :)
