### ISSUE TITLE
Pyephem appears to ignore the TLE second derivative of the mean motion

### ISSUE THREAD

**Issue by amaurea** [brandon-rhodes/pyephem#153]
The properties of an object read by readtle are `_M`, `_ap`, `_decay`, `_drag`, `_e`, `_epoch`, `_inc` , `_n`, `_orbit`, and `_raan`. These correspond to almost all the interesting elements in the TLE data. But it looks like the second derivative of the mean motion, from column 45–52 in line 1 of the TLE, is neither read nor stored.

Perhaps that element just isn't necessary, but I did a test where I took two adjacent TLE elements and computed their difference as a function of time, and their difference looks like a parabola, like one would expect if a second order term is missing. However, since I haven't compared the pyephem behavior to other implementations, this might be due to inherent inaccuracy in the TLE description rather than that term in particular.

**Comment by brandon-rhodes** [comment]
As far as I know, the element is not necessary, but if you do want to double-check, try generating some orbits with another program or tool as you hand-edit the TLE to vary that parameter. If you do find another tool changing its predictions, then make a new comment here on this issue giving those results, plus a small script of your own that shows PyEphem's for comparison. Thanks!

**Comment by amaurea** [comment]
I see. I have checked it against the reference SGP4 implementation via the sgp4 python wrapper now. Only the latitude is easily available there because it returns results in an inertial coordinate system, but that latitude is identical to pyephem's even when the element in question is non-zero, such as the very first few TLEs for the ISS, for example this one:

    1 25544U 98067A   98324.89267077  .00616830  11572-4  29139-3 0    84
    2 25544  51.5947 165.1012 0122649  89.2072 272.3014 16.05443269   101

So this was a false alarm.

Maybe if there were some sort of forum or IRC channel I could have asked there instead of raising this as an issue, since I wasn't sure that it was a problem with pyephem.

**Comment by brandon-rhodes** [comment]
Don't worry! Your question is a valid one and it wasn't any more trouble for me (or another PyEphem contributor) to type the answer here than it would have been for us to type it somewhere else — and it keeps all of the conversation centered in one channel rather than making us keep up with several.

Feel free to follow up with more conversation here, but I'm going to close the issue because I just discovered this paragraph on the Celestrak site:

>    Field 1.9 represents the first derivative of the mean motion divided by two, in units of revolutions per day2, and field 1.10 represents the second derivative of the mean motion divided by six, in units of revolutions per day3. Together, these two fields give a second-order picture of how the mean motion is changing with time. However, these two fields are not used by the SGP4/SDP4 orbital models (only by the simpler SGP model) and, therefore, serve no real purpose.

https://celestrak.com/columns/v04n03/

So think we have a definite answer to your question now! Thanks for your interest in PyEphem.
