### ISSUE TITLE
Inconsistent interpretation of degrees vs radians based on the type used

### ISSUE THREAD

**Issue by Manishearth** [brandon-rhodes/pyephem#157]
When specifying angle values like latitudes and longitudes, Ephem will interpret them as radians if specified as a float, and as degrees if specified as a string.

So:

```python
obs = ephem.Observer()
obs.lon = -118.0
# not the same as
obs.lon = "-118.0"
```

which seems easy to mix up

**Comment by Manishearth** [comment]
Code responsible is https://github.com/brandon-rhodes/pyephem/blob/f96daf12d4f815be92e0caa52611b444517b9e0d/extensions/_libastro.c#L661-L703

**Comment by Manishearth** [comment]
Fix might be to simply divide by `efactor` for the number case?

**Comment by brandon-rhodes** [comment]
Alas, this can't now be fixed without breaking existing PyEphem programs — everyone would suddenly get bad results back from scripts that have been working for years.

You can take a look at Skyfield to see a newer library for astronomy where I didn't make the terrible UX error of auto-choosing units based on whether a string or float is used, which was terrible design on my part!

I'll keep this issue open to remind me to put something at the top of the PyEphem docs to mention Skyfield.

**Comment by brandon-rhodes** [comment]
All right, I finally got my courage up and deprecated PyEphem! I tried to be friendly in the new text on the front page, and explain that what I had thought would be a feature (you can use radians! you can use degrees!) had wound up being an inconvenience instead.

Thank you for raising this issue and reminding me that the time had come to update the web site to reflect the fact that PyEphem has problems and that there are better alternatives today!

**Comment by Manishearth** [comment]
Thanks! Would it be possible to fix this with a breaking change, releasing a new major version?

**Comment by Manishearth** [comment]
(or a package called ephem2)

**Comment by brandon-rhodes** [comment]
A new major version would still break too many programs; I suspect most people using ephem just depend on it without a `<=` of the current major version.

An alternative package name is an interesting idea. When I next communicate with the other maintainers, I will bring up the idea and see what they think!
