### ISSUE TITLE
AttributeError: module 'ephem' has no attribute 'to_timezone'

### ISSUE THREAD

**Issue by Fengzi21** [brandon-rhodes/pyephem#159]
Help, please
I am learning the tutorial of ephem, and I run the code in Jupyter notebook with python 3 version. but I get  an AttributeError:  `AttributeError: module 'ephem' has no attribute 'to_timezone'`. How can I fix it?

**Comment by brandon-rhodes** [comment]
There's the chance that you're competing with PyEphem by naming your own file `ephem.py`?

**Comment by brandon-rhodes** [comment]
@Fengzi21 — I am going to close this temporarily pending further updates from you about the problem. Feel free to re-open as soon as you have more information, if there are further steps we can take to try fixing that error for you!
