### ISSUE TITLE
sublat & sublong available for all bodies

### ISSUE THREAD

**Issue by darkstar007** [brandon-rhodes/pyephem#16]
It would be really useful to me if all the bodies in pyephem had the sublat & sublong fields so that they were all in a common ECF coord system.

Thanks,

Matt

**Comment by brandon-rhodes** [comment]
For any future readers who happen by this old issue, the corresponding fully supported Skyfield feature is its `subpoint()` method:

http://localhost:8002/api-position.html#skyfield.positionlib.Geocentric.subpoint
