### ISSUE TITLE
Help needed with moon tracking (Wrong position)

### ISSUE THREAD

**Issue by TurtleForGaming** [brandon-rhodes/pyephem#160]
So I'm trying to setup a satellite tracking system I firstly started to track the iss which prove to be unsuccesful. To verify that my tracking was correct I started tracking the moon  with this code

```
from datetime import datetime
import ephem
import  math
import time

iss = ephem.readtle('ISS',
    '1 25544U 98067A   19039.55403633  .00016717  00000-0  10270-3 0  9008',
    '2 25544  51.6404 280.9282 0005479   3.8234 356.2959 15.53222475 35269'
)

dpr = 180.0 / math.pi

place = ephem.Observer()
place.lon = 47.9667
place.lat = 7.4
place.elevation = 300
place.date = datetime.utcnow()

moon = ephem.Moon(place)

while True:
	place.date =  ephem.Date(ephem.localtime(ephem.now()))
	iss.compute(place)
	moon.compute(place)
	# print (iss.az * dpr , iss.alt * dpr)
	print (moon.az * dpr, moon.alt  * dpr)
	time.sleep(.1)
```

how ever the code give me results like this: `(127.19111336543878, 31.105173253858307)`  but the problem is that the moon is in plain west (The elevation is approximatively correct) at the time of writing that helps me think that there is an error in my code I just don't know where.

(Utc at the time of writing: `datetime.datetime(2019, 2, 12, 22, 57, 40, 353000)`)

**Comment by brandon-rhodes** [comment]
If you are in France, then I'd check whether the latitude and longitude are swapped. :)

**Comment by TurtleForGaming** [comment]
Well I tried to swap latitude and longitude after changing `ephem.Moon(place)`for `ephem.Sun(place)` nad it's approximatively 90° off still

**Comment by TurtleForGaming** [comment]
And now approximatively 135°

**Comment by barrycarter** [comment]
```
from datetime import datetime
import ephem
import  math
import time

iss = ephem.readtle('ISS',
                        '1 25544U 98067A   19039.55403633  .00016717  00000-0  \
10270-3 0  9008',
                        '2 25544  51.6404 280.9282 0005479   3.8234 356.2959 15\
.53222475 35269'
                    )

dpr = 180.0 / math.pi

place = ephem.Observer()
place.lon = 7.4/dpr 
place.lat = 47.9667/dpr 
place.elevation = 300
# place.date = datetime.utcnow() 

moon = ephem.Moon(place)


place.date =  ephem.Date('2019-02-12 22:57:40');
# ephem.Date(ephem.localtime(ephem.now()))
iss.compute(place)
moon.compute(place)
print (moon.az * dpr, moon.alt  * dpr)
time.sleep(.1)

```

yields the correct result. In addition to the lat/lon switch, you forgot to divide by dpr

**Comment by TurtleForGaming** [comment]
Okay I did'nt known that you have to divide the latitude / longitude. Now it gives much better results the elevation if correct but the azimuth is still 23° off according to two phone compass apps pointing at the moon.

**Comment by TurtleForGaming** [comment]
Holy shit I'm so dumb while trouble shooting I set `place.date` to localtime and not UTC. It work now. Thanks a lot for the help
