### ISSUE TITLE
Wheels for newer Pythons on Windows

### ISSUE THREAD

**Issue by ktosiek** [brandon-rhodes/pyephem#161]
Currently Appveyor only builds wheels for Python 2.7, 3.3 and 3.4. It would be nice to also get wheels for 3.5+.

**Comment by brandon-rhodes** [comment]
I'll take a look this weekend and see if that can be easily accomplished.

**Comment by brandon-rhodes** [comment]
I've run across a wonderful new project:

https://github.com/joerick/cibuildwheel

It's allowed me to set up builds on Travis CI and Appveyor and make the first new release in several years, by providing me with Mac and Windows binary wheels. I'll hopefully be able to make regular releases from now on as bugs are fixed.
