### ISSUE TITLE
Reproducing data from American Ephemeris

### ISSUE THREAD

**Issue by ReblochonMasque** [brandon-rhodes/pyephem#162]
### [edit] sorry, I'll check skyfield instead, and ask another question there, if I need to.

Hello @brandon-rhodes ,

This is a novice question.
  
I would like to use `pyephem` to reproduce the data found in the tables in "The American Ephemeris 1950-2050" by Neil F. Michelsen & Rique Pottenger, and use it for astrological calculations.

What would be the correct approach?

Thank you

![201907 - ephemerides](https://user-images.githubusercontent.com/6275531/61990618-942b3580-b076-11e9-8986-f4f33aac107a.png)

**Comment by brandon-rhodes** [comment]
> sorry, I'll check skyfield instead, and ask another question there, if I need to

Understood — I'll close this issue, then.
