### ISSUE TITLE
Memory leak in `readdb()`?

### ISSUE THREAD

**Issue by Lyalpha** [brandon-rhodes/pyephem#166]
```
s = "Ceres,e,10.59023200,80.29715900,73.77147500,2.76871121,0.21393783,0.07712851,141.25175400,2020.13934426,2000,3.40000000,0.15000000"

while True: 
    x = ephem.readdb(s)
```
appears to continuously eat up memory for me on `v3.7.7.0`.

**Comment by brandon-rhodes** [comment]
I can confirm! It's been a long time since I've been in that code but I'll see what I can do.

**Comment by brandon-rhodes** [comment]
@Lyalpha  — Could you try
```
pip install https://github.com/brandon-rhodes/pyephem/archive/master.zip
```
and let me know if my tweak fixed the memory leak? Thanks!

**Comment by Lyalpha** [comment]
Seems to be working! Really excellent response, thanks so much.

**Comment by brandon-rhodes** [comment]
Great! I'll plan to get a release out later this month, if no earlier.
