### ISSUE TITLE
Observer.copy() missing from documentation and incompatible with copy.copy()

### ISSUE THREAD

**Issue by baldodo** [brandon-rhodes/pyephem#174]
Hi,

I needed some method to get a copy of an Observer object.
As I suspected, I was not the first to ask and I found out by looking at past issues that you added an Observer.copy() method.

But there are IMHO two further issues:
- I did not find this in the documentation of PyEphem (no mention of a  copy method)
- as far as i understand python "philosophy", you probably should have added a `__copy__()` method instead of `copy()`

At first I tried the `copy()` method from the copy standard module :
```
import copy
import ephem

observer=ephem.Observer()
observer.lat,observer.lon='45','0'
...
obs2=copy.copy(observer)
```
It raises a pickle error because there is no `__copy__()` method for Observer and for some reason pickle module will not work with Observer object.

I am aware that `obs2=observer.copy()` solves my problem, but as far as I understand python it is not the "canonical way" to do it.
Admittedly I am no python expert ; I could be wrong about this.

**Comment by brandon-rhodes** [comment]
> I did not find this in the documentation of PyEphem…

That’s a good idea, I’ll add it the next time I go in to update and re-upload PyEphem’s documentation!

> the copy standard module…

I had forgotten about that module, so there is indeed no support for it in PyEphem. Interesting. I’ll see, the next time I’m in the code, whether I can easily support both copy methods without too much extra code to support.

**Comment by brandon-rhodes** [comment]
I've updated the code to document `copy()` and support Python's copy module, and the change should go out in the next release.
