### ISSUE TITLE
de'orbited satellite has elevation when calculated from tle

### ISSUE THREAD

**Issue by mahtin** [brandon-rhodes/pyephem#175]
Looking at **STARLINK-1220**, I see the following TLE:
```
STARLINK-1220
1 45211U 20012AK  20069.91667824  .00723224  00000-0  41594-2 0  9993
2 45211  53.0024 162.4808 0027451 118.7601 331.9927 15.75746283  3703
```
However ...
```
    tle_rec = ephem.readtle(name, line1, line2)
    tle_rec.compute()
    print(tle_rec.elevation)
```
... produces `364145470` (which of course, isn't right). For other deorbit'ed satellites I get `RuntimeError` and hence no Long/Lat or Elevation pair; but not for this one.

Any thoughts? Am I doing something wrong when trying to detect a deorbit'ed satellite?

**Comment by brandon-rhodes** [comment]
The satellite's epoch is Mar 9, so we are a few weeks past the window when I would expect its TLE to give meaningful results, whether de-orbited or not. If you draw a graph of the elevation from Mar 9 til now, is the value unreasonable to start with, or does it go crazy at a specific date?

**Comment by mahtin** [comment]
Thank you for pointing that out. I added this check:
```
    some_days_ago = datetime.date.today() - datetime.timedelta(21)
    d = ephem.Date(s['date'].replace('T',' ')).datetime().date()
    if d < some_days_ago:
        raise RuntimeError
```
I started with 21 days; but I will tune that later.

Thanks! Great code!
