### ISSUE TITLE
Wheel support for linux aarch64 [arm64]

### ISSUE THREAD

**Issue by odidev** [brandon-rhodes/pyephem#185]
Summary
Installing pyephem on aarch64 via pip using command "pip3 install pyephem" tries to build wheel from source code

Problem description
pyephem doesn't have wheel for aarch64 on PyPI repository. So, while installing pyephem via pip on aarch64, pip builds wheel for same resulting in it takes more time to install pyephem. Making wheel available for aarch64 will benefit aarch64 users by minimizing pyephem installation time.

Expected Output
Pip should be able to download pyephem wheel from PyPI repository rather than building it from source code.

@pyephem-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make pyephem wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by brandon-rhodes** [comment]
Thanks for asking! This project uses a third-party build tool and build service — it looks like it’s currently backed by Appveyor:

https://github.com/joerick/cibuildwheel

https://github.com/brandon-rhodes/pyephem/blob/master/appveyor.yml

Wheels for the new architecture will be appropriate when cibuildwheel adds support. Let’s leave this issue open until Apple hardware becomes available and cibuildwheel gets upgraded.

**Comment by odidev** [comment]
@brandon-rhodes, what are your thoughts on using qemu to build aarch64 artifacts?

**Comment by brandon-rhodes** [comment]
I would prefer to leave the details of building to cibuildtool. It looks like it has aarch64 support now, judging from the grid:

https://github.com/joerick/cibuildwheel

I expect we simply need a pull request that turns it on — except that I'm not sure if the Travis build integration even works any more? We might need to migrate to GitHub Actions before any more builds take place, in any case.

**Comment by brandon-rhodes** [comment]
A Python 3.9 package for aarch64 is now available! Let me know if you have any trouble installing it.
