### ISSUE TITLE
Add example of how to print decimal degrees 

### ISSUE THREAD

**Issue by jidanni** [brandon-rhodes/pyephem#188]
/usr/lib/python3/dist-packages/ephem/doc/angle.rst
etc. are great. Except they go on and on never giving an
**example of how to print decimal degrees** angles

which is apparently done via

```
print('%s %f %s' % (p.date, v.az*180/math.pi, v.alt*180/math.pi))
2021/2/22 09:30:00 256.705065 4.989858304289461
```

It's as if we are in the golden age of clocks, and nobody ever heard
about decimal degrees.

**Comment by brandon-rhodes** [comment]
I agree, I do keep seeing decimal degrees more and more often — Google searches for city latitude and longitude, for example, always seem to return decimal degrees.

A little bit of history: the 1990s astronomy library `libastro` that PyEphem is built on top of provided no option for decimal degrees, a limitation that PyEphem inherited. It showed everything in minutes and seconds:

![image](https://user-images.githubusercontent.com/166162/108590387-48fc0600-7331-11eb-9542-de616206b353.png)

If someone had time, they could add attributes `.degrees` and `.hours` to PyEphem angle objects. For the moment, though, I’ll update the docs.
