### ISSUE TITLE
Document that .horizon does not affect .alt, .az

### ISSUE THREAD

**Issue by jidanni** [brandon-rhodes/pyephem#191]
quick.rst mentions .horizon, .alt, .az .
It also needs to mention:
.horizon does not affect .alt, .az,
as can be seen from this program, which always prints the same two
values.

```
import ephem
import math

a = ephem.Observer()
for h in 0, 777777:
    a.horizon = h
    s = ephem.Sun(a)
    print(s.alt)
```

**Comment by brandon-rhodes** [comment]
The section on `alt` and `az` doesn’t mention `.horizon`, I don’t think — so, to make sure I understand your request: you would like a mention of `.horizon` to be added to that section for the first time, to state that it has nothing to do with the values they return?

**Comment by jidanni** [comment]
Yes, and ... all I know is some of the pages mention `.horizon`, and some of the pages mention `.alt`, `.az`,
So I just picked the one that mentions both as perhaps the place to place the warning.
Of course the more pages you put the warning, the better.

**Comment by brandon-rhodes** [comment]
The quick reference does mention them both. I'll plan to add a statement about alt, az, and horizon before the next release.
