### ISSUE TITLE
Incorrect examples code in documentation

### ISSUE THREAD

**Issue by JohnPreston** [brandon-rhodes/pyephem#192]
Hello,

I am rather new to all this and started to play around with these different libraries to build my own GO-TO telescope system.
So far the moon seems work great, but typically another example in the docs is `Mars` and turns out `Mars` is not just declared in ephem

The only two other planets found are Jupiter and Saturn, coming from `_libastro` but I could not find a way to delcare new planets.

The moon works for me for now but I thought I'd point out the code in the docs does not seem to work.

Thank you!

**Comment by brandon-rhodes** [comment]
> The moon works for me for now but I thought I'd point out the code in the docs does not seem to work.

Since the docs include many examples, I am not sure which one is causing you trouble. Could you show the code that is not working on your computer, and show the error that it produces? Thanks!

**Comment by JohnPreston** [comment]
Hi @brandon-rhodes 
Thanks for replying so quickly.

It might be a false alarm as, after re-creating the whole venv, it seemed to work fine with 

```python
>>> import ephem
>>> mars = ephem.Mars()
>>> mars.compute('2007/10/02 00:50:22')
>>> print mars.ra, mars.dec
6:05:56.34 23:23:40.0
>>> ephem.constellation(mars)
('Gem', 'Gemini')
```
which originally did not work for me...

However, in the library, I could not find a reference to Mars which is something that led me to think there might have been a discrepancy after lib docs updates (I know I do find broken shells in my docs after an upgrade myself)

Where does the `Mars` declaration come from ? I could not find a class or variable in the lib?

**Comment by brandon-rhodes** [comment]
I'm glad your example script is now working for you! I'll go ahead and close the issue.

The Mars class comes from this code:
```
for index, classname, name in _libastro.builtin_planets():
    exec('''
class %(name)s(_libastro.%(classname)s):
    "Create a Body instance representing %(name)s"
    __planet__ = %(index)r
''' % dict(name=name, classname=classname, index=index))
```
It's the C code in `builtin_planets()` that can actually see which planets `libastro` supports.
