### ISSUE TITLE
Missing pip package for python 3.9 aarch64

### ISSUE THREAD

**Issue by Wuestenschiff** [brandon-rhodes/pyephem#197]
Installing on a rasberry pi running Arch linux fails with: 
```
ERROR: Could not find a version that satisfies the requirement ephem
ERROR: No matching distribution found for ephem
```
Installing on a arm64 laptop works though so I suppose aarch64 is the problem. It did work last time with python 3.8 though.

**Comment by brandon-rhodes** [comment]
The service that was building PyEphem binaries, Travis CI .org, is shutting down and being migrated to Travis CI .com — my guess is that this project needs to migrate to GitHub Actions soon. I'm not sure the old Travis logic can produce Python 3.9 binaries. But just in case, I've asked Travis to re-run the build of the most recent `release` commit. We’ll see if any new packages show up on PyPI or not!

**Comment by brandon-rhodes** [comment]
Welp. That didn’t last long.

https://travis-ci.org/github/brandon-rhodes/python-sgp4/builds/753532687

**Comment by Wuestenschiff** [comment]
That's first class reaction time! You think there will be a 3.9 version in the near future or should I look into downgrading to 3.8 for the time beeing? (I use it on a embedded solution were this is the only app)

**Comment by brandon-rhodes** [comment]
Go ahead and downgrade to 3.8 so that you can gave moving again! I have a few other projects underway that are in the way of my returning immediately to this project to try to get the CI rewritten. Let’s keep this issue open, though, to remind me that a re-release is needed soon!

**Comment by brandon-rhodes** [comment]
A Python 3.9 package for aarch64 is now available! Let me know if you have any trouble installing it.
