### ISSUE TITLE
Newton iteration getting stuck

### ISSUE THREAD

**Issue by odysseus9672** [brandon-rhodes/pyephem#201]
I'm using ephem to calculate the time targets are above a maximum zenith angle at  an observatory using the functions `previous_rising` and `next_setting`. At certain maximum zenith angles the newton iteration in the function `newton` is diverging. I'm preparing a pull request with a suggested fix.

**Comment by odysseus9672** [comment]
Should be fixed by pull request #202 . I will supply a test case later, if requested.

**Comment by brandon-rhodes** [comment]
Yes, a test case always turns out to be necessary, to prevent me from accidentally breaking a feature in the future, when I return to code years later and think "this looks a little complex" and simplify it in a way that works for my use cases but creates snags for edge cases like this one. Plus, the test case will let me examine the behavior in question and examine how the routine was breaking myself. Thanks!

**Comment by odysseus9672** [comment]
Here's a short script that is pulled out from code meant to test a source's uptime above a certain zenith angle horizon.  If you stick some print statements in the Newton's iteration you'll find that it diverges to `inf` and then gets stuck in the while loop without the ability to exit.

```
import ephem

ra0 = ephem.hours("0.0")
dec0=ephem.degrees("-7.509765625")

baseobs = ephem.Observer()
baseobs.lat='25.652939'
baseobs.lon='106.856594'
baseobs.horizon="55:00:00.0"

datestr='2020/01/01'

getlocal = ephem.Observer()
getlocal.lon, getlocal.lat = baseobs.lon, baseobs.lat
getlocal.date = baseobs.date

body = ephem.FixedBody()
body._ra = ra0
body._dec = dec0
body._epoch = ephem.J2000
body.compute(getlocal)

baseobs.date = datestr + " 00:00:00"

trise = baseobs.previous_rising(body)
print("Running setting calculation", flush=True)
tset = baseobs.next_setting(body)
print("Succeeded", flush=True)
```

**Comment by brandon-rhodes** [comment]
Thanks for the test script! It was a big help this week as I tackled a full rewrite of the rise/set search routine. The new one is designed to be far simpler and never get stuck. If you want to try it out:
```
pip install -U https://github.com/brandon-rhodes/pyephem/archive/master.zip
```
But the install might fail depending on whether you have a compiler and the Python development tools installed? In that case, you can wait until I release a new PyEphem version with the fix, hopefully by the end of this weekend.
