### ISSUE TITLE
Update License on PyPI

### ISSUE THREAD

**Issue by elacy** [brandon-rhodes/pyephem#206]
Can you update your license here: https://pypi.org/project/ephem/ to match the license used in github?

**Comment by brandon-rhodes** [comment]
Yes! That will happen automatically at the next release; let’s keep this issue open to remind me to do a release soon, if for no other reason than to get that to update. It was in February that Elwood Downey, the author of `libastro` (that PyEphem is built on top of), surprised the XEphem mailing list by releasing the code to its community under the MIT license, and that I was able to update the license in the source code, and there hasn't been a release yet to give PyPI a version with the newly freed code.

**Comment by brandon-rhodes** [comment]
Alas, no — PyPI doesn’t allow editing of properties of old versions. They are frozen in stone and can never change once submitted.

**Comment by brandon-rhodes** [comment]
Could you outline the broader problem you're working to solve? Moving the tag would mean that developers could no longer count on the GitHub tag to give them the same GitHub files that were used to build the version of the same name on PyPI. Is there a tool you're working with that accepts tags but not hashes as GitHub source identifiers? If so then it's possible I could create a new tag for you, but knowing the broader problem you're trying to solve might at least help me pick a good name (so I don't forget and delete the tag later!).

**Comment by brandon-rhodes** [comment]
(Good news: someone just discovered a serious bug that makes PyEphem hang, so I'll probably set aside another project to try getting it fixed, in which case a release will happen soon, and the new version should have the MIT license once it hits PyPI. Assuming that I can get CI working again; it was, alas, broken the last time I saw it run, and I haven't had time to track down why yet. We'll see what happens!)

**Comment by brandon-rhodes** [comment]
Version 4.0.0 is out with the new license!
