### ISSUE TITLE
C header files missing from 4.0.0 source distribution

### ISSUE THREAD

**Issue by mwcraig** [brandon-rhodes/pyephem#208]
The source distribution on pypi is missing all of the C header files, I think because of this line in `MANIFEST.in`: https://github.com/brandon-rhodes/pyephem/blob/master/MANIFEST.in#L4

I noticed it because the conda-forge build was broken https://github.com/conda-forge/ephem-feedstock/pull/13

**Comment by brandon-rhodes** [comment]
Thanks for letting me know! I've pushed a new 4.0.0.1 that should correctly include the header files in the renamed directory.

**Comment by brandon-rhodes** [comment]
(It will probably be a half-hour or so before the build is complete and the new version appears on PyPI.)

**Comment by mwcraig** [comment]
Excellent, thanks!
