### ISSUE TITLE
PYTHONOPTIMIZE=2 breaks __init__.py

### ISSUE THREAD

**Issue by nicolaerosia** [brandon-rhodes/pyephem#213]
Hello,

It seems that setting the env variable `PYTHONOPTIMIZE=2` will break this line, https://github.com/brandon-rhodes/pyephem/blob/master/ephem/__init__.py#L254 as it will discard docstrings
https://docs.python.org/3/using/cmdline.html#cmdoption-oo

```
  File "/usr/local/lib/python3.9/site-packages/ephem/__init__.py", line 267, in <module>
    class Observer(_libastro.Observer):
  File "/usr/local/lib/python3.9/site-packages/ephem/__init__.py", line 502, in Observer
    def previous_rising(self, body, start=None, use_center=False):
  File "/usr/local/lib/python3.9/site-packages/ephem/__init__.py", line 254, in describe_riset_search
    method.__doc__ += """, returning its date.
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

**Comment by brandon-rhodes** [comment]
Yes — that's true for most of my packages, since they use docstrings as documentation. Can your build script unset that environment variable before running `setup.py`? It will be awkward to go through all my projects making that same edit, so let's double check first whether your build environment can be improved before concluding that new releases are the only option. Thanks!

**Comment by nicolaerosia** [comment]
well, I was experimenting with `PYTHONOPTIMIZE` to see whether it affects in any way the performance, so I set it deliberately. To be honest I am now a bit confused that you mention setup time and `setup.py`, I have it set during _runtime_ and it looks like this method is being called everytime the library gets important (it's `__init__.py`...)

I think we could use `hasattr` to check if it exists `__doc__`, e.g.
```python
def describe_riset_search(method):
    if not hasattr(method, __doc__):
        return method

    [...]
```

**Comment by brandon-rhodes** [comment]
> To be honest I am now a bit confused that you mention setup time and setup.py …

Alas! I think I had two editors open at once, and switched to the wrong one, which had the `setup.py` open from a whole different project (sgp4), where it runs `sgp4.__doc__.split('\n', 1)` to grab the module docstring. So please ignore my earlier comment!

Yes, the `describe_riset_search()` decorator is runtime, and a quick `if` statement like you suggest would help it survive the lack of a docstring. I'll go try adding one.

Once you added that `if` statement and got the code running, was it any faster thanks to the `PYTHONOPTIMIZE` setting?

**Comment by nicolaerosia** [comment]
cool, thanks!
