### ISSUE TITLE
Rounding in time

### ISSUE THREAD

**Issue by Bernmeister** [brandon-rhodes/pyephem#214]
When extracting the time from an ```ephem.Date```, I managed to choose an exact date/time which results in some evil rounding:

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import ephem

ephemNow = ephem.Date( "2021/09/24 13:00" )
print( ephemNow ) # Correct
print( ephemNow.tuple() ) # The hour/minute/second are incorrect.
print( ephemNow.datetime().hour ) # Prints 12 rather than 13.
print( ephemNow.tuple()[ 3 ] ) # Prints 12 rather than 13.
```

Result:

```python3
2021/9/24 13:00:00
(2021, 9, 24, 12, 59, 59.99999979045242)
12
12
```

Unfortunately at the point this issue occurs, I am dealing with ```ephem.Date()``` rather than the original ```datetime``` so the "damage" is done.  I'm wanting to take the current date/time and then adjust forwards to a pre-defined hour.  The larger picture is that I want to look for satellite passes, limited to a time window set by the user.  So if I start my search loop at a particular date/time, I need to move the start of the search up to the time set by the user.

For example, if the current date/time is "2021/09/24 11:23", and the user has set a start searching at "13" hours, I want to bump the start time to "2021/09/24 13:00".  

Sorry @brandon-rhodes , I find all the good ones!

**Comment by brandon-rhodes** [comment]
1. So far as I know the string representation, which is rounded, and the tuple representation, which is raw, cannot be mixed for exactly the reason you've run into here: because the slightest difference down at the last decimal can put the date in a different bigger unit up at the top, like a different hour, day, or year.
2. Math on dates is done in floating point mode. So, `ephem.Date(my_date + 1.0/24.0)` would be my guess for advancing the date by an hour.

If you try out step 2 and it works, then let's think about how to update the Quick Reference (if those are the docs you were using) to make both of these points available to users.

**Comment by Bernmeister** [comment]
Updated the code to include version numbers which I neglected first time around...

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import ephem, sys

print( "pyephem:", ephem.__version__ )
print( "python:", sys.version )
print()

# Offending date
ephemNow = ephem.Date( "2021/09/24 13:00" )
print( ephemNow ) # Correct
print( ephemNow.tuple() ) # The hour/minute/second are incorrect.
print( ephemNow.datetime().hour ) # Prints 12 rather than 13.
print( ephemNow.tuple()[ 3 ] ) # Prints 12 rather than 13.

print()

# Same issue
ephemNowPlusOneHour = ephem.Date( ephemNow + 1.0 / 24.0 )
print( ephemNowPlusOneHour )
print( ephemNowPlusOneHour.tuple() ) # The hour/minute/second are incorrect.
print( ephemNowPlusOneHour.datetime().hour ) # Prints 13 rather than 14.
print( ephemNowPlusOneHour.tuple()[ 3 ] ) # Prints 13 rather than 14.
```

```
pyephem: 3.7.6.0
python: 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0]

2021/9/24 13:00:00
(2021, 9, 24, 12, 59, 59.99999979045242)
12
12

2021/9/24 14:00:00
(2021, 9, 24, 13, 59, 59.99999958090484)
13
13
```

In reality, my ```ephemNow``` comes from a call to ```datetime.datetime.utcnow()```.  The string usage was for me to test code as I was going along...and stumbled into this issue.

So I take your point about using ```ephem.Date( ephemNow + 1.0 / 24.0 )``` to add an hour: that should be safe.  I guess that I am concerned I have hit this issue and am unsure it this will ever occur under normal circumstances (going from ```datetime``` to ```ephem.Date```) or is only possible by going from ```str``` to ```ephem.Date```?

I was using the [quick reference](https://rhodesmill.org/pyephem/quick.html#dates), [tutorial](https://rhodesmill.org/pyephem/tutorial.html#computing-with-dates) and [ephem.Date](https://rhodesmill.org/pyephem/date.html).  In the last link, I did read about rounding but that was down in sub-seconds so didn't expect it to ripple up to H/M/S, particularly given I wasn't flipping back and forth between  ```str``` and ```ephem.Date```.

**Comment by Bernmeister** [comment]
Tried this:

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import ephem
from datetime import datetime

utcNow = datetime.strptime( "2021/09/24 13:00", "%Y/%m/%d %H:%M" )
ephemNow = ephem.Date( utcNow )
print( ephemNow ) # Correct
print( ephemNow.tuple() ) # The hour/minute/second are incorrect.
print( ephemNow.datetime().hour ) # Prints 12 rather than 13.
print( ephemNow.tuple()[ 3 ] ) # Prints 12 rather than 13.
```

Same result:

```python
2021/9/24 13:00:00
(2021, 9, 24, 12, 59, 59.99999979045242)
12
12
```

Was hoping that if I started with a ```datetime``` I'd get lucky...dammit!

**Comment by Bernmeister** [comment]
Just touching on adding an hour using ```ephem.Date(my_date + 1.0/24.0)```: it is not that I want to add an hour; I want to take a date/time, inspect the hour and adjust forward to a nominated hour (and rollover to the next day if required).

As in the example at the start, given "2021/09/24 11:23" in which the hour is 11, I want "2021/09/24 13:00" (because 13 was specified).  If given "2021/09/24 21:23" in which the hour is 21, I want "2021/09/25 13:00" (the day rolls over to the next and have again set the hour to 13).  Of course, this is all done down at the ```ephem.Date``` level rather than using ```str```...but I'm here because I was testing things as I was going along and hit this snag.

**Comment by Bernmeister** [comment]
Have implemented what I originally wanted in this snippet:

```python
startHour = 6 # UTC
endHour = 11 # UTC
currentDateTime = ephem.Date( datetime.utcnow() )

currentDateTimeTuple = currentDateTime.tuple()
currentHour = currentDateTime.tuple()[ 3 ]
if currentHour < startHour:
    currentDateTimeTuple = currentDateTime.tuple()
    currentDateTime = ephem.Date( ( currentDateTimeTuple[ 0 ], currentDateTimeTuple[ 1 ], currentDateTimeTuple[ 2 ], startHour, 0, 0 ) )

elif currentHour >= endHour:
    currentDateTime = ephem.Date( currentDateTime + 1 )
    currentDateTimeTuple = currentDateTime.tuple()
    currentDateTime = ephem.Date( ( currentDateTimeTuple[ 0 ], currentDateTimeTuple[ 1 ], currentDateTimeTuple[ 2 ], startHour, 0, 0 ) )
```

Does the job and I have to assume/hope that as I am starting with ```ephem.Date( datetime.utcnow() )```, there will be none of the rounding shenanigans!  To test for other times, I suppose I can use something similar to ```ephem.Date( n + ephem.minute )``` rather than with a ```str```.

Thanks, as always, for your help @brandon-rhodes.  Your call if you want to add something to the documentation about this (and I'm happy for the issue to be closed).

**Comment by brandon-rhodes** [comment]
@Bernmeister — It took a couple of hours more than I expected (my C must be a bit rusty!) but I think I’ve worked out a fix: having PyEphem always round to the nearest microsecond when turning date floats into actual dates and times. You’ll see several places in the docs where numbers had trailing noise, or even rounded to the previous date or time, that all get fixed with this improvement:

77b43b17541cae87e3e646deaeca9b54c4543cba

I’ll think about making a release soon to get this out. Let me know if you think it looks like it would work!

**Comment by Bernmeister** [comment]
@brandon-rhodes It's been quite a few years since I last compiled, let alone wrote, C!  I'll have to wait until the release (which is not urgent for me) to test.

If the tuple from my example script got rounded from right to left, instead of ```(2021, 9, 24, 12, 59, 59.99999979045242)``` it presumably would look like ```(2021, 9, 24, 13, 0, 0)``` as a result of your fix?

**Comment by brandon-rhodes** [comment]
I just ran your script against it, and it printed `(2021, 9, 24, 13, 0, 0.0)`, yes. Success!

**Comment by Bernmeister** [comment]
Winner winner chicken dinner!
