### ISSUE TITLE
How to calculate Geocentric degrees?

### ISSUE THREAD

**Issue by manujchandra** [brandon-rhodes/pyephem#234]
Greetings,

On March 27, 2003 the geocentric longitude for Mars was 284.0°

I am using the following code, which I believe is giving the heliocentric coordinates:

```
import ephem
mars = ephem.Mars()
mars.compute('2003/3/27')
mars.hlon

4.2477006912231445
```

Thanks!

**Comment by drbitboy** [comment]
I think you want mars.a_ra or mars.ra, which is in radians,

See https://rhodesmill.org/pyephem/quick#body-compute-observer and https://rhodesmill.org/pyephem/radec

**Comment by manujchandra** [comment]
Hi,

Thanks for your answer.

I have been able to do this:

```
import ephem
import numpy as np

mars = ephem.Mars()

mumbai = ephem.Observer()
mumbai.lat = '19.076090'
mumbai.lon = '72.877426'
mumbai.elevation = 36
mumbai.date = '2003/3/27 14:00'

mars.compute(mumbai)

# Geocentric
np.degrees(mars.ra)
285.6505129427214
```

However when I use flatlib I get 284.3576733592345 and using kerykeion gives 284.2135430082993

```
from flatlib.datetime import Datetime
from flatlib.geopos import GeoPos
from flatlib.chart import Chart
from flatlib.chart import const

date = Datetime('2003/03/27', '14:00', '+00:00')
pos = GeoPos('72E52:57', '19N04:22') 
chart = Chart(date, pos)

obj = chart.getObject(const.MARS)

obj.isRetrograde()

obj.lon
284.3576733592345

```
```
import kerykeion as kr
from kerykeion.utilities.charts import MakeSvgInstance

# Args: Name, year, month, day, hour, minuts, city, nation(optional)
kanye = kr.KrInstance("Kanye", 2003, 3, 27, 14, 00, "Mumbai")
Kanye birth location: Mumbai, 19.07283, 72.88261

kanye.mars

{'name': 'Mars',
 'quality': 'Cardinal',
 'element': 'Earth',
 'sign': 'Cap',
 'sign_num': 9,
 'position': 14.213543008299325,
 'abs_pos': 284.2135430082993,
 'emoji': '♑️',
 'house': '6th House',
 'retrograde': False}


```

So I was wondering why I am getting 1 degree or so extra?

Kind Regards,

**Comment by brandon-rhodes** [comment]
> So I was wondering why I am getting 1 degree or so extra?

For one thing, you latitude and longitudes look different. Maybe you could start by making them agree?

And when looking at a difference between astronomy libraries, it's good to bring in a third opinion. Maybe you could try the JPL HORIZONS online tool, and see which coordinate it returns?

**Comment by manujchandra** [comment]
Hi,

I have changed the lat long to :
```
mumbai.lat = '19.07283'
mumbai.lon = '72.88261'
```
Which is a value returned by kerykeion. But I still get ~285

I could not figure out how to use JPL HORIZONS. But I have a book also in which its written that "On March 27, 2003 the geocentric longitude for Mars was 284.0°".

So 3 sources are giving ~284 degrees, but in pyephm I am getting 285.

Thanks.

**Comment by manujchandra** [comment]
Thanks for your help. 

In the documentation, some examples can be provided for different types of longitudes and latitudes in a "cook-book" like format. This could help newcomers to the library and disambiguate different uses cases.

Regards,
