### ISSUE TITLE
One day off when calculating next full moon phase

### ISSUE THREAD

**Issue by manujchandra** [brandon-rhodes/pyephem#235]
Hello,

As per https://www.timeanddate.com/moon/phases/india/new-delhi?year=2022

The next full moon after 14th June in New Delhi will be on 14 Jul 00:07

When I compute this using pyephm I get 13 July 18:37:35
```
import ephem

d2 = ephem.next_full_moon('2022/6/15')
print(d2)
```
I understand that Full Moon is a whole earth phenomenon so it should be not too dependent on the observer.

Why is this discrepancy in dates occurring? (For many other dates the date is matching but not the time)

Thanks!

**Comment by drbitboy** [comment]
I think pyephem is reporting the time in the UTC time zone; at that point the New Delhi local time (UTC+0530 ) will be five and a half hours "later," so 2022-07-13 18:37 GMT (UTC+0000) is the same as 2022-07-14 00:07 IST (UTC+0530)

Perhaps pyephem has a way to convert to local time (IST).

**Comment by manujchandra** [comment]
Hi 

Thanks, this worked.

Regards,
