### ISSUE TITLE
Ephemeris for spacecraft observations

### ISSUE THREAD

**Issue by migueldvb** [brandon-rhodes/pyephem#43]
For satellite observations, it would be useful to have the ephemeris and body attributes (elong, phase...) in the position of the center of the spacecraft providing its location with respect to the Earth that is generally available from JPL Horizons.

**Comment by brandon-rhodes** [comment]
Having looked over the C code, the fact that Earth Satellites do not support attributes like phase is built into the structure of the library itself — it’s not a member of their `struct` data structures. As PyEphem is designed simply to wrap "libastro", not rewrite it, it makes the most sense for the omission to remain in place. Users who want the extra expense of elongation and phase — which would slow down satellite computations for everyone simply trying to compute range and angle, I think? — can simply ask for those angular separation values themselves with `separation()` and a `Sun` object.

I am open to the idea of adding Earth satellite phase-and-elongation numbers to Skyfield, which is written in pure Python and is easier to add features to. Feel free to open an issue over there if you are still interested. Thanks!

(Wow, it takes me a long time to say “no”. Five years, in this case? Sheesh.)
