### ISSUE TITLE
planet coordinate systems (moving observer to another planet) ?

### ISSUE THREAD

**Issue by ifmihai** [brandon-rhodes/pyephem#48]
I'm new to pyephem.
I searched the docs, and it appears it's not possible, at least for now.

would it be possible to move the observer to another planet?

I'm interested right now mostly in calculating declination of venus (for example) as seen from jupiter (for example)
Declination => find moments when venus crosses jupiter's equator

The problem is I'm not a physics guy, or an advanced math guy, so I try to find a library to be able to do this

Any help or insight on this?

**Comment by drbitboy** [comment]
Brandon, going back over old items; I may get an opportunity to use SPICE for astrological calculation.

What crossing in 2009 did SPICE miss?  I set the step size to 10d, so it certainly is possible, but I see three in my results [here](https://github.com/drbitboy/vj/blob/master/vj.txt).

**Comment by brandon-rhodes** [comment]
Comparing your list with the short list in my code:

http://nbviewer.jupyter.org/gist/brandon-rhodes/60503689abeef7fc099c

it's the 2009-08 crossing that's not marked on my graph as a SPICE-detected crossing. I can't now decide, all these years later, whether I was cutting and pasting from a SPICE result set of my own (or someone else's besides yours), or whether I made a cut and paste error that left 2009-08 out. So unless we find new evidence, let's assume that the error was mine, and that SPICE in fact found that crossing!
