### ISSUE TITLE
Provide binary wheels for Windows

### ISSUE THREAD

**Issue by neothemachine** [brandon-rhodes/pyephem#54]
On PyPI there are currently Windows binaries in form of .exe installers. Please switch to using wheels so that pyephem can be easily installed under Windows with `pip install pyephem`.

**Comment by tritium21** [comment]
If you are making the windows binaries with tox, I have a tox config that will just build and make a all the dists for you.  I could even build them for you, if you like.

```
[tox]
envlist = sdist,py26,py27,py32,py33,py34,a26,a27,a32,a33,a34
toxworkdir = {toxinidir}/.tox_kit_wheel
[testenv:sdist]
commands=python setup.py sdist --formats=zip,bztar,gztar
[testenv]
commands=
    {envpython} setup.py build bdist_egg bdist_wininst bdist_wheel
deps=
    wheel
    setuptools>=6.0.0
[testenv:a26]
basepython=C:\Python26.64\python.exe
[testenv:a27]
basepython=C:\Python27.64\python.exe
[testenv:a32]
basepython=C:\Python32.64\python.exe
[testenv:a33]
basepython=C:\Python33.64\python.exe
[testenv:a34]
basepython=C:\Python34.64\python.exe
```

**Comment by tritium21** [comment]
http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyephem

**Comment by hugovk** [comment]
This can be closed now there are wheels available: https://pypi.python.org/pypi/pyephem/

I've successfully installed with wheels for Windows.

**Comment by brandon-rhodes** [comment]
Oh, thank you — I forgot to come back and close the issue once I used Appveyor to build and release the wheels!
