### ISSUE TITLE
Non-consecutive rise,transit,set times

### ISSUE THREAD

**Issue by dmopalmer** [brandon-rhodes/pyephem#63]
This is a re-opening of issue #38  (Observer.next_pass returns set time that is before rise time)

That was closed because the satellite was a GEO bird that therefore had poorly-defined rise,transit set times.

Here is a simple case with a LEO satellite (the ISS) which also shows the problem.  It may be partially due to the fact that, at the compute() time, the satellite is above the horizon.

```
# Minimal example of non-consecutive rise,transit,set
import ephem
print("ephem.__version__ = ",ephem.__version__)

iss = ephem.readtle("ISS (ZARYA)",
  "1 25544U 98067A   03097.78853147  .00021906  00000-0  28403-3 0  8652",
  "2 25544  51.6361  13.7980 0004256  35.6671  59.2566 15.58778559250029")

gatech = ephem.Observer()
gatech.lon, gatech.lat = '-84.39733', '33.775867'
gatech.date = '2003/3/23 03:17:11'
iss.compute(gatech)
np = gatech.next_pass(iss)
next_pass_times = np[::2]
print("Next pass rise,transit,set",list((d.datetime().strftime("%H:%M:%S ") for d in next_pass_times)))
```

Output is 

```
ephem.__version__ =  3.7.5.3
Next pass rise,transit,set ['04:49:53 ', '03:18:54 ', '03:20:18 ']
```

If you use a start time 
`gatech.date = '2003/3/23 03:00:11'` 
(at which time ISS is below the horizon), you get a valid, monotonically increasing rise,transit,set
`['03:10:48 ', '03:15:29 ', '03:20:11 ']`
Note that the transit time is several minutes away from that for the pathological case.

**Comment by MikeJohnshoy** [comment]
I ran into this too.  The nextpass method is pretty useful.  You pass it a time, and get rise time and set time in return.  If you happen to have passed it a time where you are in mid-pass, you get the set time back along with the next rise time - so you may have to look out for that case and handle it.  You know you have access between the time you gave it and the set time.  All good.

But if you are unlucky in picking your start time, you may get a rise time in the future with a set time that is in the past.  This seems a little more awkward to handle.. 

I ran into this when using nextpass to get an access, and then trying to move just a little bit past the set time I got and call nextpass again and so on.  You want to try not to hit near a set time when you calll it!   That works once you get under way, but you still might be unlucky in picking your first time.

Here is some sample code and output ... 


============================================================================

import ephem

line0 = 'IRIDIUM'
line1 = '1 25469U 98051C   09119.61415140 -.00000218  00000-0 -84793-4 0  4781'
line2 = '2 25469  86.4029 183.4052 0002522  86.7221 273.4294 14.34215064557061'
iridium = ephem.readtle(line0, line1, line2)

site = ephem.Observer()
site.lat = 38
site.lon = -77
site.date = '2009/5/1 00:00:00'

while site.date < ephem.Date('2009/5/10 00:00:00'):
    info = site.next_pass(iridium)
    site.date = site.date + ephem.minute
    if site.date > info[4]:     
        print('Yikes - set time is in the past')
        print('Date:', site.date, '  Rise:', info[0], '  Set:', info[4])

======================================================

Yikes - set time is in the past
Date: 2009/5/8 15:38:00   Rise: 2009/5/9 02:25:17   Set: 2009/5/8 15:37:15
Yikes - set time is in the past
Date: 2009/5/9 02:41:00   Rise: 2009/5/9 04:07:19   Set: 2009/5/9 02:40:19
Yikes - set time is in the past
Date: 2009/5/9 04:20:00   Rise: 2009/5/9 13:10:54   Set: 2009/5/9 04:19:37
Yikes - set time is in the past
Date: 2009/5/9 13:21:00   Rise: 2009/5/9 14:48:53   Set: 2009/5/9 13:20:25
Yikes - set time is in the past
Date: 2009/5/9 15:05:00   Rise: 2009/5/9 16:33:35   Set: 2009/5/9 15:04:20
Yikes - set time is in the past
Date: 2009/5/9 16:40:00   Rise: 2009/5/10 01:52:36   Set: 2009/5/9 16:39:21

**Comment by dmopalmer** [comment]
I just did a code inspection, so I haven't built and tested it, but I think the solution may be as simple as:
- file libastro-3.7.7/riset_cir.c
- line 207
- function e_riset_cir

Change:
	    } else if (a0 > 0 && a1 < 0 && !set) {
To
	    } else if (a0 > 0 && a1 < 0 && !set && rise) {

This is where it is walking forward in time to find a (rise event) and a (set event).  The change is to have it walk forward until it finds a (rise event) and a (set event when there has already been a rise event).

**Comment by dmopalmer** [comment]
This at least fixes the minimal test case at the top

    Next pass rise,transit,set ['04:49:50 ', '04:52:55 ', '04:55:59 ']

I didn't dig in to adding a test case for this, but the previous tests seem to show no regression, if I am doing it right:

    Ran 90 tests in 1.605s
    
    OK

**Comment by dmopalmer** [comment]
Added test case

```
======================================================================
FAIL: test_next_pass_consecutive (tests.test_satellite.SatelliteTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/palmer/repo/others/myforks/pyephem/ephem/tests/test_satellite.py", line 49, in test_next_pass_consecutive
    self.assertAlmostEqual(ephem.Date('2009/4/30 5:06:39'), tt, 3)
AssertionError: 39931.71295138889 != 39931.160826866515 within 3 places

----------------------------------------------------------------------
Ran 91 tests in 1.563s
```
Fix and bump version to 3.7.6.1
```
Ran 91 tests in 1.500s

OK
```
Submitting pull request.

**Comment by MikeJohnshoy** [comment]
Neat to hear you're working on it. It seems like it would be good to 
list all the possible reasonable and OK results:

1. rise_time > time_now,  set_time > time_now AND after rise_time   
(this being the case we think of most often when we ask for next rise 
and set)
2. rise_time > time_now,  set_time > time_now BUT rise_time is after 
set_time (the case where the satellite is above the horizon when we look)
3. no rise_time or set_time

The results I don't understand (because we expect ephem to return the 
next events):
4. rise_time > time_now,  set_time < time_now
5. rise_time < time_now,  set_time > time_now

I have definitely seen Case # 4 happen - I check for that sort of result 
and work around it.

I don't think you should change anything that would affect the first 
three reasonable results.

**Comment by dmopalmer** [comment]
I don't agree that your case 2 is what it should return.

Given that the function is called 'next_pass', the semantics should require that it gives you a pass that is a complete rise,transit,set sequence that is in the future, i.e.

    time_now < time_rise < time_transit < time_set

This means that if the satellite is already above the horizon, next_pass()[4] is not the time it next sets.

Internally, the next_pass code calculates the transit time by trying to take the time of maximum altitude between the rise and set times, which is just a mess if the altitude is negative and concave-up between those times.

Separate next_rise(), next_transit(), next_set() functions might be useful, but that is should not be what next_pass returns n the already-up case.

**Comment by MikeJohnshoy** [comment]
Well, but given that that is the way it is, and it's documented and 
already handled in people's code, you might not want to change it.

If you do change it, would you add a new function to determine if the 
satellite is above the horizon at time_now?

**Comment by dmopalmer** [comment]
The way it is now is broken, and routinely causes bug reports complaining about set time before rise time
https://bugs.launchpad.net/pyephem/+bug/572402, #38, and this one

The way it is documented (http://rhodesmill.org/pyephem/quick.html) is "determines when it will next cross above the horizon."

In order to find whether a satellite is above the horizon at time_now,

    sat.compute(site)
    if (sat.alt >= site.horizon):
        do_up_stuff

A bigger problem is probably that the fix is inside libastro, which is the xepehem library code, so it will revert on the xephem update.

**Comment by dmopalmer** [comment]
I just got a reply from xephem's Elwood Downey:

> This change will break the way XEphem is defined to function for Earth satellites. In XEphem, all events (rise, set and transit) are the strictly _next_ events. So if the time in the Main window is between rise and transit of a given pass, rise info will be for the _next_ pass; if the time is between transit and set, both rise and transit will be for the _next_ pass. However, you are correct in that sometimes transit can be for the current pass for a short while after it occurs.

So my pull request modifying the library probably has too many bad side effects.

It would still be useful to have a function that gives the next pass (now < rise < transit < set).  Maybe by adding a flag to the next_pass() function that specifies that behavior.

**Comment by brandon-rhodes** [comment]
@dmopalmer ­— thank you for finding a better example than the geostationary satellite. The better choice of target is what has permitted the conversation to advance farther than before, up to and including a comment from the esteemed Elwood Downey himself!

Let me know if you would like to outline a specific change to the code that, while not diverging from the guarantees built into `libastro`, would let PyEphem offer a more flexible situation for its users. Thanks for all of this work on the issue!

**Comment by dmopalmer** [comment]
I have a new candidate pull request which does not modify libastro.  It modifies the
python in __init__.py .  I have closed my previous pull request.

obs.next_pass(sat) gives a single pass with consecutive (rise, culminate, set).  

obs.next_pass(sat, singlepass=False) gives (next_rise, next_culminate, next_set)

I chose to make the default case different from the current behavior because I believe that the singlepass=False case is almost always unwanted and unexpected.

However, when I submit it, test_github_58 fails on windows machines.  I don't see how that could be my fault.  (That's what the word 'bug' means.)  Did the test fail before?  The two new tests I have both pass under all builds.

**Comment by dmopalmer** [comment]
The code still has problems with edge-case satellites, especially high, eccentric orbits that have ground tracks like this:
![orbitdisplay aspx](https://cloud.githubusercontent.com/assets/1822143/10196872/4775e670-6752-11e5-8488-3cc71d371bc9.png)
(This is a BREEZE-M rocket body catalog number 28925
http://www.heavens-above.com/orbit.aspx?satid=28925  )

The latest commit now throws a `ValueError("this software is having trouble with those satellite parameters")` if the rise,culm,set are non-consecutive.

**Comment by girtsf** [comment]
Just ran into this issue as well. Getting `set_time < rise_time` was quite unexpected.

**Comment by brandon-rhodes** [comment]
Good evening, @girtsf! @dmopalmer had been making such good progress, and working through the various cases, that I'd been reading his progress but not commenting, waiting to see if he defeated all the edge cases he was running across — but then got snagged in the fact that the master branch was failing against Windows 64-bit.

I'll try to decide in the coming week whether I'm likely to want to revive this line of development for PyEphem, or instead to port the work over to Skyfield, a far better-designed astronomy library I've been working on. If I have hours to spend on satellites, they might be better used over there — I'll try to report back next weekend. Thanks for bumping this issue!

**Comment by brandon-rhodes** [comment]
I'll close the issue for now, and a future issue can be opened if folks are running into issues with the new behavior.
