### ISSUE TITLE
previous_rising() skips sunrise times at the north pole

### ISSUE THREAD

**Issue by ninneman** [brandon-rhodes/pyephem#65]
Using the latest PyEphem pulled directly from Github, I'm attempting to compute sunrise times at Earth's north pole, which occur only once per year (in March). I've discovered that previous_rising() skips over the sunrise for one or two years, depending on which year I use as the starting point.

This program demonstrates the error:

```
#!/usr/bin/python3

import ephem
import datetime

def get_previous_rise(observer, body):
    while True:
        try:
            rise_time = observer.previous_rising(body)
            break
        except (ephem.AlwaysUpError, ephem.NeverUpError):
            observer.date = observer.previous_antitransit(body)
    return rise_time

np = ephem.Observer()
np.lon = 0 * ephem.degree
np.lat = 90 * ephem.degree
np.elevation = 0
sun = ephem.Sun()

for year in range(1900, 2100):
    start_time = ephem.Date(datetime.datetime(year, 6, 1))
    np.date = start_time
    rise_time = get_previous_rise(np, sun)
    difference = start_time.datetime() - rise_time.datetime()
    print("for {0}, sunrise was {1} previous".format(year, difference))
```

Which gives output like:

```
for 1900, sunrise was 804 days, 15:41:08.341447 previous
for 1901, sunrise was 73 days, 22:24:44.625040 previous
for 1902, sunrise was 73 days, 16:32:29.915412 previous
for 1903, sunrise was 438 days, 16:32:29.915412 previous
for 1904, sunrise was 804 days, 16:32:29.915412 previous
for 1905, sunrise was 73 days, 22:52:27.044984 previous
for 1906, sunrise was 73 days, 16:55:54.082062 previous
for 1907, sunrise was 438 days, 16:55:54.082062 previous
for 1908, sunrise was 804 days, 16:55:54.082062 previous
for 1909, sunrise was 73 days, 23:33:51.867867 previous
for 1910, sunrise was 73 days, 17:45:51.699219 previous
for 1911, sunrise was 73 days, 11:54:03.381875 previous
for 1912, sunrise was 439 days, 11:54:03.381875 previous
for 1913, sunrise was 804 days, 11:54:03.381875 previous
for 1914, sunrise was 73 days, 18:36:47.585368 previous
for 1915, sunrise was 73 days, 12:56:34.473033 previous
for 1916, sunrise was 439 days, 12:56:34.473033 previous
```

and so on. Note that "previous" means previous to June 1, a date I hard-coded into the program above. The sun is definitely up at that date. The values around 73 days are probably correct, since June 1 - 73 days is roughly the March equinox. The others obviously aren't right at all. Interestingly, changing the latitude to 89.9 makes this problem disappear. I'm continuing my investigation.

**Comment by ninneman** [comment]
That 10-hour thing was supposed to be a placeholder. My reasoning was that 10 hours is less than half of 24 hours, so I'm guaranteed not to skip over a zero by walking that interval.

**Comment by ninneman** [comment]
My latest PR only fails two of the regression tests. I made a dumb mistake in the last one that gave wrong results everywhere except the north and south poles.

**Comment by brandon-rhodes** [comment]
I have just tried out your new algorithm, and I think that it might still miss certain sunrises. For example, the sunrise in 1905 if viewed from close to, but not exactly at, the pole:

```
import ephem

polar = ephem.Observer()
polar.lon = 0 * ephem.degree
polar.lat = 89.9 * ephem.degree
polar.elevation = 0

sun = ephem.Sun()

for date in [
        '1905/3/18',
        '1905/3/19',
        '1905/3/20',
        '1905/3/21',
        ]:
    polar.date = date
    try:
        polar.previous_rising(sun)
    except Exception as e:
        print e
```

The output that I get from this script, when on your branch (at least as shown in the pull request), is:

```
'Sun' culminates below the horizon at 1905/3/17 14:40:00
'Sun' culminates below the horizon at 1905/3/18 14:41:54
'Sun' is still above the horizon at 1905/3/19 21:31:46
'Sun' is still above the horizon at 1905/3/20 21:30:00
```

Do you see the same thing, or do you get a different result?

**Comment by barrycarter** [comment]
Thought: the sun's changing declination (which causes all this odd 
behavior) can never increase by more than .12 degrees per day.

Perhaps change the algorithm to assume an up-to-.01 degrees/hour (ie, 
twice the max value) change in declination to find the check interval, 
instead of a fixed 6 hour period?

Sort of like a Newton's method.

**Comment by brandon-rhodes** [comment]
I suspect that for high latitudes we are supposed to adjust the algorithm to find the minimum of the second derivative each day, to find the local maximum that the sun creates as it dips and then starts upward again.

I wonder if it is time for me to invest in the book behind the Astronomical Almanac, in the hopes that they already have a perfect algorithm for doing sunrises from even high latitudes?

http://www.amazon.com/Explanatory-Supplement-Astronomical-Almanac-Urban/dp/1891389858/

**Comment by ninneman** [comment]
> Do you see the same thing, or do you get a different result?

Yep, I see the same behavior. However, try this:
```
import ephem

polar = ephem.Observer()
polar.lon = 0 * ephem.degree
polar.lat = 89.9 * ephem.degree
polar.elevation = 0

sun = ephem.Sun()

for date in [
        '1905/3/18 06:00',
        '1905/3/19 06:00',
        '1905/3/20 06:00',
        '1905/3/21 06:00',
        ]:
    polar.date = date
    try:
        risetime = polar.previous_rising(sun)
        print("rise detected at {0}".format(risetime))
    except Exception as e:
        print(e)
```
Which for me produces:
```
'Sun' culminates below the horizon at 1905/3/17 14:40:00
rise detected at 1905/3/19 04:08:50
'Sun' is still above the horizon at 1905/3/19 21:31:46
'Sun' is still above the horizon at 1905/3/20 21:30:00
```
What this tells me is that the root-finding is failing or succeeding depending on the initial guesses.

**Comment by ninneman** [comment]
Nope, it wasn't the root-finding algorithm. It's much simpler. Since sunrise is at 1905/3/19 at 04:08, it would only be caught by searching backward from 1905/3/20 in your test code. But since the sun upper-culminates above the horizon at 1905/3/19 21:31:46 and errors out accordingly, the search never sees 04:08.

So the problem--if there is one--is in the CircumpolarError decision code. However, there is similar behavior in the current transit-based rise and set calculator. The canonical way to work around it is to re-search starting from the datetime where the error left off. That could work here too.

**Comment by brandon-rhodes** [comment]
I am going to close this issue for now. While I do plan to keep PyEphem updated so that it can compile under new versions of Python as they come out, I am not planning to invest my time in its old solvers, particularly for edge cases like the Poles; my attention instead needs to be focused on the more robust routines in Skyfield.

If anyone reading this later does develop a solution along with tests, though, I'm not averse to having them comment here and submitting the code for consideration!
