### ISSUE TITLE
RA and Decs again, pyEphem vs Skyfield

### ISSUE THREAD

**Issue by readee** [brandon-rhodes/pyephem#74]
Hi Brandon

I'm still trying to use pyEphem and/or now skyfield to generate RA/Decs from TLEs for
a given date and place, so that I can match up trails on images with known orbits. The images have built in world coordinate systems (WCS) so I know the J2000.0 RA/Dec at a given point on the images so I want as close to possible equivalent RA/Dec from pyEphem, which from previous questions I believe is the .ra and .dec attributes/objects.

So for pyEphem I have

```
sat=ephem.readtle("SATNAME ", \
                  "1 38356U 12030A   14148.90924578  .00000000  00000-0  10000-3 0  5678",\
                  "2 38356   0.0481  47.9760 0002933 358.9451 332.7970  1.00270012  3866")
gatech = ephem.Observer()
gatech.lon, gatech.lat = '-5.47322222', '19.82561111'
gatech.elevation = 4194
gatech.date = '2014/01/02 07:05:52'
sat.compute(gatech)
print 'a_ra=',sat.a_ra,'a_dec=',sat.a_dec,'g_ra=',sat.g_ra,'g_dec=',sat.g_dec,'ra=',sat.ra,'dec=',sat.dec
```

which gives
```
a_ra= 1:15:36.95 a_dec= -2:32:29.9 g_ra= 1:14:10.55 g_dec= 0:06:09.8 ra= 1:16:19.75 dec= -2:28:04.6
```
doing what I assume to be the equivalent in skyfield
```
text = """
SATNAME
1 38356U 12030A   14148.90924578  .00000000  00000-0  10000-3 0  5678
2 38356   0.0481  47.9760 0002933 358.9451 332.7970  1.00270012  3866
"""
bluffton = earth.topos('19.82561111 N', '-5.47322222 E', elevation_m=4194.0)
tup = (2014, 1, 2, 7, 05, 52)
sat = earth.satellite(text)
astrometric = bluffton(utc=tup).observe(sat)

ra, dec, distance = astrometric.radec()
print(ra.hstr())
print(dec.dstr())
```
I get 01h 15m 44.42s -02deg 43' 00.9" which is close but not identical to pyEphem's
values of ra= 1:16:19.75 dec= -2:28:04.6.

Am I using skyfield wrongly and/or are the differences expected and/or with the accuracy of the calculations.

Thanks as always
Ad

**Comment by brandon-rhodes** [comment]
That agreement is quite close for two different libraries — the SGP4 algorithm is generally only accurate to within a few kilometers, and that's only if you stay right near the epoch date of the TLE entry, so I think that these two positions are within each other's error bounds. One way to check: learn the rate at which the satellite was moving in km, and use that number to try pulling a position from, say, 3km ahead in its future and then 3km back in its past. That will tell you “how big,” in RA and Dec degrees, a “few km” is for this particular observer and satellite. My guess is that you will see a bigger difference from a 3km change in position than from this difference between libraries — but, if not, then maybe we should peer more deeply into how they are implementing SGP4, or else why similar SGP4 output is being mapped to different RA and Dec.

(A stray memory is making me think that PyEphem considers the Earth to be a sphere for the purposes of satellite positions, which might have an effect, though I can't recall how big.)

**Comment by readee** [comment]
Hi Brandon

Just looking at  the Dec, they disagree by just under 15 arcmin so about 0.25 degrees. Which is around 1/1000th (0.0007) of the length/circumference of the orbit, assuming a distance of 40000km then they are out by a minimum of around 175km. But likely the example or implementation I've done is not sensible/wrong. 
cheers
Ad

**Comment by brandon-rhodes** [comment]
I often see the statement that “The SGP4 model has an error ~1 km at epoch and grows at ~1–3 km per day” — and, in fact, it is currently part of the Wikipedia article on SGP4, although I cannot find that statement in the source provided in the corresponding footnote.

But if the guideline is correct that SGP4 predictions must be kept fairly close to the epoch of the TLE to be accurate, then your problem might be that your TLE is for late May but you are asking it for a day back in January:

```
print sat.epoch.utc_jpl()
#=> A.D. 2014-May-27 21:49:18.8354 UT
```

If I move the month and day of your two dates to “5” and “27”, the month and day of the TLE elements when it should be most accurate, I see a disagreement of only about 0.2 km:

```
import ephem
sat=ephem.readtle("SATNAME ", \
                  "1 38356U 12030A   14148.90924578  .00000000  00000-0  10000-3 0  5678",\
                  "2 38356   0.0481  47.9760 0002933 358.9451 332.7970  1.00270012  3866")
gatech = ephem.Observer()
gatech.lon, gatech.lat = '-5.47322222', '19.82561111'
gatech.elevation = 4194
gatech.date = '2014/05/27 07:05:52'
gatech.pressure = 0.0
sat.compute(gatech)

from skyfield.api import earth

text = """
SATNAME
1 38356U 12030A   14148.90924578  .00000000  00000-0  10000-3 0  5678
2 38356   0.0481  47.9760 0002933 358.9451 332.7970  1.00270012  3866
"""
sat2 = earth.satellite(text)
print sat2
bluffton = earth.topos('19.82561111 N', '-5.47322222 E', elevation_m=4194.0)
#tup = (2014, 1, 2, 7, 05, 52)
tup = (2014, 5, 27, 7, 05, 52)

apparent = bluffton(utc=tup).observe(sat2)
ra, dec, distance = apparent.radec()

print 'Topocentric J2000 coordinates:'
print
print '(PyEphem) a_ra=', sat.a_ra, 'a_dec=', sat.a_dec
print '(Skyfield) ra:', ra.hstr(), ' dec:', dec.dstr()
print

ra, dec, distance = apparent.radec(epoch='date')

print 'Topocentric epoch-of-date coordinates:'
print
print '(PyEphem) ra=',sat.ra,'dec=',sat.dec
print '(Skyfield) ra:', ra.hstr(), ' dec: ', dec.dstr()
```

Which produces:

```
Topocentric J2000 coordinates:

(PyEphem) a_ra= 10:32:43.23 a_dec= -2:27:42.4
(Skyfield) ra: 10h 32m 51.05s  dec: -02deg 27' 43.1"

Topocentric epoch-of-date coordinates:

(PyEphem) ra= 10:33:27.20 dec= -2:32:10.5
(Skyfield) ra: 10h 33m 35.46s  dec:  -02deg 32' 17.0"
```

The solution, if you want its position back in January, is probably to find some older TLE elements which will be valid for that date. I will try to make the TLE epoch easier to print out so that it is easier to check against when loading up TLE elements!

**Comment by readee** [comment]
Hi Brandon

Thanks again it does look much closer with a TLE closer in time to the obs. The difference though is about 2 arcmin which at a range of  48,000 km I make to be about 27km. But maybe that is now within the tolerances.

Cheers
Ad

**Comment by brandon-rhodes** [comment]
That does sound within the tolerances for SGP4, so I am — provisionally — going to try closing this issue for now. But I do happen to be working heavily on the Earth-location observer code at the moment, and will come back and re-open this issue if I find any snags that might suggest that closer agreement could be achieved here.

But, for the moment, my guess is that this is a combination of SGP4's quirks plus PyEphem's incorrect use of a sphere for the Earth.
