### ISSUE TITLE
XEphem 3.7.7 is out...

### ISSUE THREAD

**Issue by Bernmeister** [brandon-rhodes/pyephem#81]
Hi Brandon,

Related to issue [47] (https://github.com/brandon-rhodes/pyephem/issues/47) and given you have so much free time on your hands, I thought you might like to know that XEphem 3.7.7 is out as of August 2015.

The rather brief changelog mentions a satellite fix, but I'm sure over the last year I've seen interim posts about other underlying fixes which didn't make the final changelog.

As usual, job very well done!

Thanks again, 

Bernard.

**Comment by brandon-rhodes** [comment]
Good thing I got 3.7.6.0 out the door last Wednesday! It got to enjoy being an up-to-date release for, what, three or four days before it became outdated?

I'll pull the 3.7.7 code and see if there are other changes and fixes to be pulled into PyEphem. Thanks!

**Comment by Bernmeister** [comment]
I didn't think to look at GitHub for a release - I only checked [Rhodes Mill](http://rhodesmill.org/pyephem).  Thanks for the new release - I'll give it a good thrashing!

**Comment by brandon-rhodes** [comment]
All right, I merged in 3.7.7 — it looks like, except for a few whitespace adjustments, the main change is that a magnitude gets computed in a situation where it previously didn't:

fa648561ce7567bb067aa9a4532fe83b93a43bda

I don't see anything about “magnitude” in the XEphem change log, though, so it's hard to tell if the change is important or warrants a release. Any ideas?

**Comment by Bernmeister** [comment]
If that's all the changes, then I'd not bother with a release.  Put your feet up!

**Comment by Elwell** [comment]
>
> If that's all the changes, then I'd not bother with a release. Put your
> feet up!
>

As an aside, the 3.7.6.0 release is in bleeding edge fedora if anyone wants
to test it.
https://koji.fedoraproject.org/koji/buildinfo?buildID=682345

I'll probably punt it into EPEL 7, but possibly not into EPEL6 and below -
don't want to break anything

Andrew

**Comment by brandon-rhodes** [comment]
Thank you, @Elwell!
