### ISSUE TITLE
Decayed satellite causing code to hang

### ISSUE THREAD

**Issue by EdGrrr** [brandon-rhodes/pyephem#82]
I have been trying to plot the position of a large number of satellites using pyephem from a database.  However, when I try and plot the following, it gets stuck in an infinite loop (making it difficult to detect and avoid)

    import ephem
    tle = ("0 MOLNIYA 1-42",                                                                                                                       
           "1 11007U 78080A   15223.34532704  .99999999  58108-5  10171-2 0  9994",                                                                
           "2 11007 062.2871 061.7119 0627378 263.5453 276.0639 15.20396923291974")
    obj = ephem.readtle(*tle)
    obj.compute()
    obj.sublong

This satellite has recently decayed (last few weeks), which presumably is why it is causing this code to hang.  Is there a way to detect a decayed satellite before this hang?

**Comment by wenzul** [comment]
For me it's

```
>>> import ephem
>>> tle = ("0 MOLNIYA 1-42",
...        "1 11007U 78080A   15223.34532704  .99999999  58108-5  10171-2 0  9994",
...        "2 11007 062.2871 061.7119 0627378 263.5453 276.0639 15.20396923291974")
>>> obj = ephem.readtle(*tle)
>>> obj.compute()
>>> obj.sublong
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cannot compute the body's position at 2015/8/25 10:55:18
```

**Comment by EdGrrr** [comment]
Unfortunately my version doesn't raise an exception (otherwise I would deal with it as you suggested), it just hangs, which makes it difficult to deal with.

Could it be a version thing?  I am using python 2.7.9 and pyephem version 3.7.5.3

**Comment by Bernmeister** [comment]
@EdGrrr: Yes I believe it's a version thing.  As of 3.7.6.0 an exception is now raised (I just tested now on Ubuntu 14.04).

**Comment by wenzul** [comment]
Yes, Python 2.7.9. 32 Bit PyEphem 3.7.6.0.

Congratulations, your problem was already fixed. ;)

> When an Earth satellite position cannot be computed, PyEphem now raises an exception instead of freezing and locking up Python.
Source: http://rhodesmill.org/pyephem/CHANGELOG.html#version-3-7-6-0-2015-august-19

**Comment by EdGrrr** [comment]
Great, thanks!

**Comment by brandon-rhodes** [comment]
@EdGrrr I am glad that this fix might have addressed your problem! Let us know if you test and find that your bug is resolved, and we can close this issue. Thanks!

**Comment by EdGrrr** [comment]
Sorry for the slow reply - yes this is now resolved and you can close the issue.

**Comment by brandon-rhodes** [comment]
Thank you — glad that it is now working! :)
