### ISSUE TITLE
setup.py tests not running

### ISSUE THREAD

**Issue by rtphokie** [brandon-rhodes/pyephem#83]
tests no longer execute 

% python setup.py test
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'test'

**Comment by brandon-rhodes** [comment]
Sorry for the confusion! PyEphem has not supported the old `setup.py test` setuptools feature for several years. To prevent confusion in the future, I have removed the command from the 2008 changelog entry (where you might have found it?), and added up-to-date instructions to the bottom of the README:

https://github.com/brandon-rhodes/pyephem#developers

Let me know if you have any further problems, or found the command in some other old piece of documentation that I need to update. Thanks!

**Comment by rtphokie** [comment]
That's where I found it, didn't see it updated in subsequent release notes.

Thanks for updating the instructions, those work great now.
