### ISSUE TITLE
Unable to pip install on Python 3.5 under Windows 7

### ISSUE THREAD

**Issue by GGillan** [brandon-rhodes/pyephem#86]
Is it planned to release a binary for Windows? I am unable to install on Python 3.5 (32-bit), Windows 7 (64-bit), with VS Express 2013 installed and VS (Community Edition) 2015 installed, getting the "Unable to find vcvarsall.bat" error. 

Full output:

C:\Users\George>pip install pyephem
Collecting pyephem
  Using cached pyephem-3.7.6.0.tar.gz
Building wheels for collected packages: pyephem
  Running setup.py bdist_wheel for pyephem
  Complete output from command "c:\python 3.5\python.exe" -c "import setuptools;
__file__='C:\\Users\\George\\AppData\\Local\\Temp\\pip-build-h5f13p4o\\pyephem\\
setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'e
xec'))" bdist_wheel -d C:\Users\George\AppData\Local\Temp\tmpvubx6gispip-wheel-:

  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.5
  creating build\lib.win32-3.5\ephem
  copying ephem\cities.py -> build\lib.win32-3.5\ephem
  copying ephem\stars.py -> build\lib.win32-3.5\ephem
  copying ephem\__init__.py -> build\lib.win32-3.5\ephem
  creating build\lib.win32-3.5\ephem\tests
  copying ephem\tests\test_angles.py -> build\lib.win32-3.5\ephem\tests
  copying ephem\tests\test_bodies.py -> build\lib.win32-3.5\ephem\tests
  copying ephem\tests\test_cities.py -> build\lib.win32-3.5\ephem\tests
  copying ephem\tests\test_constants.py -> build\lib.win32-3.5\ephem\tests
  copying ephem\tests\test_dates.py -> build\lib.win32-3.5\ephem\tests
  copying ephem\tests\test_github_issues.py -> build\lib.win32-3.5\ephem\tests
  copying ephem\tests\test_jpl.py -> build\lib.win32-3.5\ephem\tests
  copying ephem\tests\test_launchpad_236872.py -> build\lib.win32-3.5\ephem\test
s
  copying ephem\tests\test_launchpad_244811.py -> build\lib.win32-3.5\ephem\test
s
  copying ephem\tests\test_locales.py -> build\lib.win32-3.5\ephem\tests
  copying ephem\tests\test_observers.py -> build\lib.win32-3.5\ephem\tests
  copying ephem\tests\test_rst.py -> build\lib.win32-3.5\ephem\tests
  copying ephem\tests\test_satellite.py -> build\lib.win32-3.5\ephem\tests
  copying ephem\tests\test_stars.py -> build\lib.win32-3.5\ephem\tests
  copying ephem\tests\test_usno.py -> build\lib.win32-3.5\ephem\tests
  copying ephem\tests\test_usno_equinoxes.py -> build\lib.win32-3.5\ephem\tests
  copying ephem\tests\__init__.py -> build\lib.win32-3.5\ephem\tests
  creating build\lib.win32-3.5\ephem\doc
  copying ephem\doc\angle.rst -> build\lib.win32-3.5\ephem\doc
  copying ephem\doc\catalogs.rst -> build\lib.win32-3.5\ephem\doc
  copying ephem\doc\CHANGELOG.rst -> build\lib.win32-3.5\ephem\doc
  copying ephem\doc\coordinates.rst -> build\lib.win32-3.5\ephem\doc
  copying ephem\doc\date.rst -> build\lib.win32-3.5\ephem\doc
  copying ephem\doc\examples.rst -> build\lib.win32-3.5\ephem\doc
  copying ephem\doc\faq.rst -> build\lib.win32-3.5\ephem\doc
  copying ephem\doc\index.rst -> build\lib.win32-3.5\ephem\doc
  copying ephem\doc\newton.rst -> build\lib.win32-3.5\ephem\doc
  copying ephem\doc\quick.rst -> build\lib.win32-3.5\ephem\doc
  copying ephem\doc\radec.rst -> build\lib.win32-3.5\ephem\doc
  copying ephem\doc\reference.rst -> build\lib.win32-3.5\ephem\doc
  copying ephem\doc\rise-set.rst -> build\lib.win32-3.5\ephem\doc
  copying ephem\doc\tutorial.rst -> build\lib.win32-3.5\ephem\doc
  creating build\lib.win32-3.5\ephem\tests\jpl
  copying ephem\tests\jpl\europa.txt -> build\lib.win32-3.5\ephem\tests\jpl
  copying ephem\tests\jpl\hyperion.txt -> build\lib.win32-3.5\ephem\tests\jpl
  copying ephem\tests\jpl\jupiter.txt -> build\lib.win32-3.5\ephem\tests\jpl
  copying ephem\tests\jpl\mars.txt -> build\lib.win32-3.5\ephem\tests\jpl
  copying ephem\tests\jpl\neptune.txt -> build\lib.win32-3.5\ephem\tests\jpl
  copying ephem\tests\jpl\oberon.txt -> build\lib.win32-3.5\ephem\tests\jpl
  copying ephem\tests\jpl\phobos.txt -> build\lib.win32-3.5\ephem\tests\jpl
  copying ephem\tests\jpl\saturn.txt -> build\lib.win32-3.5\ephem\tests\jpl
  copying ephem\tests\jpl\uranus.txt -> build\lib.win32-3.5\ephem\tests\jpl
  creating build\lib.win32-3.5\ephem\tests\usno
  copying ephem\tests\usno\appgeo_deneb.txt -> build\lib.win32-3.5\ephem\tests\u
sno
  copying ephem\tests\usno\appgeo_jupiter.txt -> build\lib.win32-3.5\ephem\tests
\usno
  copying ephem\tests\usno\appgeo_moon.txt -> build\lib.win32-3.5\ephem\tests\us
no
  copying ephem\tests\usno\appgeo_sun.txt -> build\lib.win32-3.5\ephem\tests\usn
o
  copying ephem\tests\usno\apptopo_deneb.txt -> build\lib.win32-3.5\ephem\tests\
usno
  copying ephem\tests\usno\apptopo_moon.txt -> build\lib.win32-3.5\ephem\tests\u
sno
  copying ephem\tests\usno\apptopo_sun.txt -> build\lib.win32-3.5\ephem\tests\us
no
  copying ephem\tests\usno\astrom_antares.txt -> build\lib.win32-3.5\ephem\tests
\usno
  copying ephem\tests\usno\astrom_mercury.txt -> build\lib.win32-3.5\ephem\tests
\usno
  copying ephem\tests\usno\astrom_neptune.txt -> build\lib.win32-3.5\ephem\tests
\usno
  copying ephem\tests\usno\moon_phases.txt -> build\lib.win32-3.5\ephem\tests\us
no
  copying ephem\tests\usno\risettran_moon.txt -> build\lib.win32-3.5\ephem\tests
\usno
  copying ephem\tests\usno\risettran_rigel.txt -> build\lib.win32-3.5\ephem\test
s\usno
  copying ephem\tests\usno\riset_moon.txt -> build\lib.win32-3.5\ephem\tests\usn
o
  copying ephem\tests\usno\riset_sun.txt -> build\lib.win32-3.5\ephem\tests\usno

  running build_ext
  building 'ephem._libastro' extension
  error: Unable to find vcvarsall.bat

  ----------------------------------------
←[31m  Failed building wheel for pyephem←[0m
Failed to build pyephem
Installing collected packages: pyephem
  Running setup.py install for pyephem
    Complete output from command "c:\python 3.5\python.exe" -c "import setuptool
s, tokenize;__file__='C:\\Users\\George\\AppData\\Local\\Temp\\pip-build-h5f13p4
o\\pyephem\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).rea
d().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\George\
AppData\Local\Temp\pip-_pd8n_rg-record\install-record.txt --single-version-exter
nally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    building 'ephem._libastro' extension
    error: Unable to find vcvarsall.bat

    ----------------------------------------
←[31mCommand ""c:\python 3.5\python.exe" -c "import setuptools, tokenize;__file_
_='C:\\Users\\George\\AppData\\Local\\Temp\\pip-build-h5f13p4o\\pyephem\\setup.p
y';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n',
 '\n'), __file__, 'exec'))" install --record C:\Users\George\AppData\Local\Temp\
pip-_pd8n_rg-record\install-record.txt --single-version-externally-managed --com
pile" failed with error code 1 in C:\Users\George\AppData\Local\Temp\pip-build-h
5f13p4o\pyephem←[0m

C:\Users\George>

**Comment by GGillan** [comment]
Found this wheel:

ephem‑3.7.6.0‑cp35‑none‑win32.whl

at

http://www.lfd.uci.edu/~gohlke/pythonlibs/

And it installed fine. Thank you!

**Comment by brandon-rhodes** [comment]
I will see if Appveyor is supporting Python 3.5 and see if I can get something built this month for 3.5 — in the meantime, thank you for sharing a link where others can find a usable package!
