### ISSUE TITLE
FixedBody() arguments are silently ignored

### ISSUE THREAD

**Issue by dmopalmer** [brandon-rhodes/pyephem#88]
In order to create a star or other FIxedBody, none of the following work:

```
wtfstar = ephem.FixedBody(ephem.Equatorial("20:06:15.457","44:27:24.6"))
wtfstar = ephem.FixedBody(ra="20:06:15.457",dec="44:27:24.6")
wtfstar = ephem.FixedBody("20:06:15.457 44:27:24.6")
```

but they silently ignore the arguments, giving a star at ra=0, dec=0 without don't throwing an error.  

In order to get a star at a given location, you have to manipulate its private members.

```
wtfstar = ephem.FixedBody()
wtfstar._ra = "20:06:15.457"
wtfstar._dec = "44:27:24.6"
```

**Comment by brandon-rhodes** [comment]
You are right! The arguments should either be used, or should throw an error. For the next version of PyEphem, I will try to implement either one or the other solution. Thanks!

**Comment by pozar87** [comment]
Hi!
Thanks for this project it saved me quite a lot of time :)
Regarding this issue I would prefer the:
```
wtfstar = ephem.FixedBody(ra="20:06:15.457",dec="44:27:24.6")
```

**Comment by brandon-rhodes** [comment]
Since I lack the time to write up full initializer code for the FixedBody, I've at least landed a fix that will report an error instead of ignoring extra arguments.
